"use client";
import { FormEvent, useEffect, useMemo, useState } from "react";

type Student={id:string;application?:{studentName?:string};enrollment?:{id:string;className?:string;section?:string}};
type Invoice={id:string;invoiceNumber:string;feeType:string;amount:number;discount:number;netAmount:number;dueDate:string;status:string;student:{application:{studentName?:string};admissionNumber?:string;className?:string};payments:{amount:number}[]};

export default function FeesPage(){const [data,setData]=useState<Invoice[]>([]),[students,setStudents]=useState<Student[]>([]),[q,setQ]=useState(""),[loading,setLoading]=useState(true),[error,setError]=useState(""),[studentId,setStudentId]=useState(""),[feeType,setFeeType]=useState("Tuition Fee"),[amount,setAmount]=useState(""),[discount,setDiscount]=useState("0"),[dueDate,setDueDate]=useState(""),[paymentInvoice,setPaymentInvoice]=useState(""),[paymentAmount,setPaymentAmount]=useState(""),[paymentMethod,setPaymentMethod]=useState("Cash"),[saving,setSaving]=useState(false);
const load=()=>fetch("/api/fees").then(async r=>{const d=await r.json();if(!r.ok)throw Error(d.error);setData(d)}).catch(e=>setError(e.message||"Unable to load fees"));
useEffect(()=>{Promise.all([load(),fetch("/api/students").then(r=>r.json()).then(setStudents).catch(()=>setError("Unable to load students."))]).finally(()=>setLoading(false))},[]);
async function createInvoice(e:FormEvent){e.preventDefault();setError("");setSaving(true);try{const r=await fetch("/api/fees",{method:"POST",headers:{"Content-Type":"application/json"},body:JSON.stringify({studentId,feeType,amount,discount,dueDate})});const d=await r.json();if(!r.ok)throw Error(d.error||"Unable to create invoice");setStudentId("");setAmount("");setDiscount("0");setDueDate("");await load()}catch(e){setError(e instanceof Error?e.message:"Unable to create invoice")}finally{setSaving(false)}}
async function recordPayment(e:FormEvent){e.preventDefault();setError("");setSaving(true);try{const r=await fetch("/api/fees",{method:"POST",headers:{"Content-Type":"application/json"},body:JSON.stringify({action:"payment",invoiceId:paymentInvoice,amount:paymentAmount,paymentMethod})});const d=await r.json();if(!r.ok)throw Error(d.error||"Unable to record payment");setPaymentInvoice("");setPaymentAmount("");await load()}catch(e){setError(e instanceof Error?e.message:"Unable to record payment")}finally{setSaving(false)}}
const filtered=useMemo(()=>data.filter(x=>[x.invoiceNumber,x.feeType,x.student?.application?.studentName,x.student?.admissionNumber].join(" ").toLowerCase().includes(q.toLowerCase())),[data,q]);const billed=data.reduce((s,x)=>s+Number(x.netAmount),0),collected=data.reduce((s,x)=>s+x.payments.reduce((a,p)=>a+Number(p.amount),0),0);
return <main className="container"><header className="admissions-header"><div><div className="eyebrow">Aghaaz School Management / Fees</div><h1>Fees</h1><p>Invoices, collections and outstanding student balances.</p></div></header><section className="admission-stats"><div className="admission-stat"><span>Total billed</span><strong>PKR {billed.toLocaleString()}</strong></div><div className="admission-stat"><span>Collected</span><strong>PKR {collected.toLocaleString()}</strong></div><div className="admission-stat"><span>Outstanding</span><strong>PKR {Math.max(0,billed-collected).toLocaleString()}</strong></div><div className="admission-stat"><span>Invoices</span><strong>{data.length}</strong></div></section>{error&&<div className="error">{error}</div>}
<section className="applications-card"><div className="table-toolbar"><div><h2>Create invoice</h2><p>Bill an enrolled student.</p></div></div><form className="form-grid" onSubmit={createInvoice}><label>Student<select className="input" value={studentId} onChange={e=>setStudentId(e.target.value)} required><option value="">Select student</option>{students.map(s=><option key={s.enrollment?.id||s.id} value={s.enrollment?.id||s.id}>{s.application?.studentName||"Unnamed"} — {s.enrollment?.className||""}</option>)}</select></label><label>Fee type<input className="input" value={feeType} onChange={e=>setFeeType(e.target.value)} required/></label><label>Amount (PKR)<input className="input" type="number" min="1" step="0.01" value={amount} onChange={e=>setAmount(e.target.value)} required/></label><label>Discount (PKR)<input className="input" type="number" min="0" step="0.01" value={discount} onChange={e=>setDiscount(e.target.value)}/></label><label>Due date<input className="input" type="date" value={dueDate} onChange={e=>setDueDate(e.target.value)} required/></label><button className="button" type="submit" disabled={saving}>{saving?"Saving…":"Create Invoice"}</button></form></section>
<section className="applications-card"><div className="table-toolbar"><div><h2>Record payment</h2><p>Collect against an outstanding invoice.</p></div></div><form className="form-grid" onSubmit={recordPayment}><label>Invoice<select className="input" value={paymentInvoice} onChange={e=>setPaymentInvoice(e.target.value)} required><option value="">Select invoice</option>{data.filter(x=>x.status!=="PAID").map(x=>{const paid=x.payments.reduce((s,p)=>s+Number(p.amount),0);return <option key={x.id} value={x.id}>{x.invoiceNumber} — {x.student?.application?.studentName||"Student"} — PKR {Math.max(0,Number(x.netAmount)-paid).toLocaleString()} due</option>})}</select></label><label>Amount (PKR)<input className="input" type="number" min="0.01" step="0.01" value={paymentAmount} onChange={e=>setPaymentAmount(e.target.value)} required/></label><label>Payment method<select className="input" value={paymentMethod} onChange={e=>setPaymentMethod(e.target.value)}><option>Cash</option><option>Bank Transfer</option><option>Card</option><option>Cheque</option><option>Online</option></select></label><button className="button" type="submit" disabled={saving}>{saving?"Saving…":"Record Payment"}</button></form></section>
<section className="applications-card"><div className="table-toolbar"><div><h2>Fee invoices</h2><p>Current invoice register.</p></div><input className="search-input" placeholder="Search invoice, student or admission no." value={q} onChange={e=>setQ(e.target.value)}/></div>{loading?<div className="empty-state">Loading fees…</div>:filtered.length===0?<div className="empty-state"><strong>No invoices found</strong><span>Create an invoice above to begin collecting fees.</span></div>:<div className="table-wrap"><table><thead><tr><th>Invoice</th><th>Student</th><th>Fee type</th><th>Amount</th><th>Due date</th><th>Status</th></tr></thead><tbody>{filtered.map(x=>{const paid=x.payments.reduce((s,p)=>s+Number(p.amount),0);const status=paid>=Number(x.netAmount)?"PAID":paid>0?"PARTIAL":x.status;return <tr key={x.id}><td><strong>{x.invoiceNumber}</strong></td><td><strong>{x.student?.application?.studentName||"—"}</strong><small>{x.student?.admissionNumber||""}</small></td><td>{x.feeType}</td><td>PKR {Number(x.netAmount).toLocaleString()}<small>Paid PKR {paid.toLocaleString()}</small></td><td>{new Date(x.dueDate).toLocaleDateString()}</td><td><span className={`status-pill ${status==="PAID"?"status-enrolled":status==="PARTIAL"?"status-payment_pending":"status-documents_pending"}`}>{status}</span></td></tr>})}</tbody></table></div>}</section></main>}
