"use client";

import Link from "next/link";
import { useEffect, useState } from "react";

type Structure = { sessions: { id: string; name: string }[]; grades: { id: string; name: string; sessionId: string }[]; subjects: { id: string; name: string; code: string }[]; sections: { id: string; name: string; gradeId: string }[]; staff: { id: string; name: string; employeeNumber: string; staffType: string }[] };
type Topic = { id: string; title: string; description: string | null; displayOrder: number; objectives: string | null; estimatedPeriods: number; plans: { id: string; academicSectionId: string; teacherStaffId: string; status: string; plannedStartDate: string | null; plannedEndDate: string | null; notes: string | null; section: { id: string; name: string } | null; teacher: { id: string; name: string } | null }[] };
type Curriculum = { id: string; academicSessionId: string; academicGradeId: string; academicSubjectId: string; title: string; description: string | null; status: string; session: { id: string; name: string } | null; grade: { id: string; name: string } | null; subject: { id: string; name: string } | null; topics: Topic[] };

export default function CurriculumPage() {
  const [structure, setStructure] = useState<Structure | null>(null);
  const [curricula, setCurricula] = useState<Curriculum[]>([]);
  const [sessionId, setSessionId] = useState(""); const [gradeId, setGradeId] = useState(""); const [subjectId, setSubjectId] = useState(""); const [sectionId, setSectionId] = useState(""); const [teacherId, setTeacherId] = useState("");
  const [title, setTitle] = useState(""); const [description, setDescription] = useState(""); const [topicTitle, setTopicTitle] = useState(""); const [objectives, setObjectives] = useState(""); const [periods, setPeriods] = useState("1");
  const [selectedCurriculum, setSelectedCurriculum] = useState(""); const [selectedTopic, setSelectedTopic] = useState(""); const [startDate, setStartDate] = useState(""); const [endDate, setEndDate] = useState("");
  const [message, setMessage] = useState(""); const [error, setError] = useState(""); const [loading, setLoading] = useState(true);

  async function load() { setLoading(true); try { const params = new URLSearchParams(); if (sessionId) params.set("sessionId", sessionId); if (gradeId) params.set("gradeId", gradeId); if (subjectId) params.set("subjectId", subjectId); if (sectionId) params.set("sectionId", sectionId); if (teacherId) params.set("teacherId", teacherId); const [s, c] = await Promise.all([fetch("/api/academic-structure"), fetch(`/api/curriculum?${params.toString()}`)]); const sj = await s.json(); const cj = await c.json(); if (!s.ok) throw new Error(sj.error); if (!c.ok) throw new Error(cj.error); setStructure({ sessions: sj.sessions || [], grades: sj.grades || [], subjects: sj.subjects || [], sections: sj.sections || [], staff: (sj.staff || []).filter((x: Structure["staff"][number]) => x.staffType === "TEACHER") }); setCurricula(cj.curricula || []); } catch (e) { setError(e instanceof Error ? e.message : "Unable to load curriculum."); } finally { setLoading(false); } }
  useEffect(() => { void load(); }, [sessionId, gradeId, subjectId, sectionId, teacherId]);
  const grades = structure?.grades.filter(x => !sessionId || x.sessionId === sessionId) || [];
  const sections = structure?.sections.filter(x => x.gradeId === gradeId) || [];
  const active = curricula.find(x => x.id === selectedCurriculum);

  async function save(body: Record<string, unknown>, success: string) { setError(""); setMessage(""); try { const r = await fetch("/api/curriculum", { method: "POST", headers: { "Content-Type": "application/json" }, body: JSON.stringify(body) }); const j = await r.json(); if (!r.ok) throw new Error(j.error); setMessage(success); await load(); return j; } catch (e) { setError(e instanceof Error ? e.message : "Unable to save."); return null; } }

  return <main className="admissions-shell">
    <header className="admissions-header"><div><div className="eyebrow">Aghaaz / Academic / Curriculum</div><h1>Curriculum & Teaching Plan</h1><p>Define what is taught, why it is taught, and when each class is expected to complete it.</p></div><Link className="button" href="/teacher-workspace">Teacher Workspace</Link></header>
    {message && <div className="success" role="status">{message}</div>}{error && <div className="error" role="alert">{error}</div>}
    <section className="panel"><div className="panel-heading"><div><h2>Academic scope</h2><p>Curriculum is anchored to the academic year, grade and subject.</p></div></div><div className="form-grid"><label>Academic year<select className="input" value={sessionId} onChange={e => { setSessionId(e.target.value); setGradeId(""); }}><option value="">All years</option>{structure?.sessions.map(x => <option key={x.id} value={x.id}>{x.name}</option>)}</select></label><label>Grade<select className="input" value={gradeId} onChange={e => { setGradeId(e.target.value); setSectionId(""); }}><option value="">All grades</option>{grades.map(x => <option key={x.id} value={x.id}>{x.name}</option>)}</select></label><label>Subject<select className="input" value={subjectId} onChange={e => setSubjectId(e.target.value)}><option value="">All subjects</option>{structure?.subjects.map(x => <option key={x.id} value={x.id}>{x.name} · {x.code}</option>)}</select></label><label>Section<select className="input" value={sectionId} onChange={e => setSectionId(e.target.value)}><option value="">All sections</option>{sections.map(x => <option key={x.id} value={x.id}>{x.name}</option>)}</select></label><label>Teacher<select className="input" value={teacherId} onChange={e => setTeacherId(e.target.value)}><option value="">All teachers</option>{structure?.staff.map(x => <option key={x.id} value={x.id}>{x.name} · {x.employeeNumber}</option>)}</select></label></div></section>

    <section className="bottom-grid"><div className="panel"><div className="panel-heading"><div><h2>New curriculum</h2><p>One curriculum per year + grade + subject.</p></div></div><label>Title<input className="input" value={title} onChange={e => setTitle(e.target.value)} placeholder="e.g. Grade 5 Mathematics" /></label><label>Description<textarea className="input" value={description} onChange={e => setDescription(e.target.value)} placeholder="Scope and learning intent" /></label><button className="primary-button" disabled={!sessionId || !gradeId || !subjectId || !title.trim()} onClick={async () => { const r = await save({ action: "CURRICULUM", academicSessionId: sessionId, academicGradeId: gradeId, academicSubjectId: subjectId, title, description }, "Curriculum created."); if (r) { setTitle(""); setDescription(""); setSelectedCurriculum(r.id); } }}>Create curriculum</button></div>
      <div className="panel"><div className="panel-heading"><div><h2>Add topic</h2><p>Topics become measurable teaching units.</p></div></div><label>Curriculum<select className="input" value={selectedCurriculum} onChange={e => setSelectedCurriculum(e.target.value)}><option value="">Select curriculum…</option>{curricula.map(x => <option key={x.id} value={x.id}>{x.grade?.name} · {x.subject?.name} · {x.title}</option>)}</select></label><label>Topic title<input className="input" value={topicTitle} onChange={e => setTopicTitle(e.target.value)} placeholder="e.g. Fractions" /></label><label>Learning objectives<textarea className="input" value={objectives} onChange={e => setObjectives(e.target.value)} placeholder="What should students know or be able to do?" /></label><label>Estimated periods<input className="input" type="number" min="1" value={periods} onChange={e => setPeriods(e.target.value)} /></label><button className="primary-button" disabled={!selectedCurriculum || !topicTitle.trim()} onClick={async () => { const r = await save({ action: "TOPIC", curriculumId: selectedCurriculum, title: topicTitle, objectives, estimatedPeriods: Number(periods) }, "Topic added."); if (r) { setTopicTitle(""); setObjectives(""); setPeriods("1"); setSelectedTopic(r.id); } }}>Add topic</button></div></section>

    <section className="applications-card"><div className="table-toolbar"><div><h2>Curriculum map</h2><p>{curricula.length} curriculum record{curricula.length === 1 ? "" : "s"} · topics and teaching progress.</p></div><button className="button" onClick={() => void load()}>Refresh</button></div>{loading ? <div className="empty-state">Loading…</div> : curricula.length === 0 ? <div className="empty-state">No curriculum yet. Create one above.</div> : <div className="table-wrap"><table><thead><tr><th>Year</th><th>Grade</th><th>Subject</th><th>Topic</th><th>Periods</th><th>Progress</th></tr></thead><tbody>{curricula.flatMap(c => c.topics.length ? c.topics.map(t => <tr key={t.id}><td>{c.session?.name}</td><td>{c.grade?.name}</td><td>{c.subject?.name}</td><td><strong>{t.title}</strong>{t.objectives && <small>{t.objectives}</small>}</td><td>{t.estimatedPeriods}</td><td>{t.plans.length ? t.plans.map(p => <div key={p.id}>{p.section?.name || "Section"} · {p.teacher?.name || "Teacher"} · <strong>{p.status}</strong></div>) : "Not planned"}</td></tr>) : [<tr key={c.id}><td>{c.session?.name}</td><td>{c.grade?.name}</td><td>{c.subject?.name}</td><td><strong>{c.title}</strong></td><td>—</td><td>Awaiting topics</td></tr>])}</tbody></table></div>}</section>

    {active && <section className="bottom-grid"><div className="panel"><div className="panel-heading"><div><h2>Plan a topic</h2><p>Assign a topic to a real section and teacher.</p></div></div><label>Topic<select className="input" value={selectedTopic} onChange={e => setSelectedTopic(e.target.value)}><option value="">Select topic…</option>{active.topics.map(t => <option key={t.id} value={t.id}>{t.title}</option>)}</select></label><label>Section<select className="input" value={sectionId} onChange={e => setSectionId(e.target.value)}><option value="">Select section…</option>{sections.map(x => <option key={x.id} value={x.id}>{x.name}</option>)}</select></label><label>Teacher<select className="input" value={teacherId} onChange={e => setTeacherId(e.target.value)}><option value="">Select teacher…</option>{structure?.staff.map(x => <option key={x.id} value={x.id}>{x.name}</option>)}</select></label><div className="form-grid"><label>Start<input className="input" type="date" value={startDate} onChange={e => setStartDate(e.target.value)} /></label><label>End<input className="input" type="date" value={endDate} onChange={e => setEndDate(e.target.value)} /></label></div><button className="primary-button" disabled={!selectedTopic || !sectionId || !teacherId} onClick={async () => { const r = await save({ action: "PLAN", topicId: selectedTopic, academicSectionId: sectionId, teacherStaffId: teacherId, plannedStartDate: startDate || null, plannedEndDate: endDate || null }, "Teaching plan saved."); if (r) { setStartDate(""); setEndDate(""); } }}>Save teaching plan</button></div><div className="panel"><div className="panel-heading"><div><h2>How this flows</h2><p>Teaching progress becomes operational data.</p></div></div><div className="activity-row"><div><strong>Curriculum</strong><small>Year + grade + subject scope</small></div></div><div className="activity-row"><div><strong>Topic</strong><small>Objectives + estimated periods</small></div></div><div className="activity-row"><div><strong>Teaching plan</strong><small>Section + teacher + planned dates</small></div></div><div className="activity-row"><div><strong>Completion</strong><small>Feeds Teacher Workspace and future Monitor signals</small></div></div></div></section>}
  </main>;
}
