"use client";

import Link from "next/link";
import { useEffect, useState } from "react";

type Band = { id: string; label: string; minPercentage: number; maxPercentage: number; points: number | null; pass: boolean; displayOrder: number };
type Scheme = { id: string; sessionId: string | null; name: string; description: string | null; active: boolean; bands: Band[] };
type Session = { id: string; name: string };

export default function GradingSettingsPage() {
  const [schemes, setSchemes] = useState<Scheme[]>([]); const [sessions, setSessions] = useState<Session[]>([]); const [sessionId, setSessionId] = useState(""); const [selected, setSelected] = useState(""); const [name, setName] = useState(""); const [description, setDescription] = useState(""); const [label, setLabel] = useState(""); const [min, setMin] = useState(""); const [max, setMax] = useState(""); const [points, setPoints] = useState(""); const [pass, setPass] = useState(true); const [error, setError] = useState(""); const [message, setMessage] = useState("");

  async function load() { try { const [s, g] = await Promise.all([fetch("/api/academic-sessions"), fetch(`/api/grading${sessionId ? `?sessionId=${encodeURIComponent(sessionId)}` : ""}`)]); const sj = await s.json(); const gj = await g.json(); if (!s.ok || !g.ok) throw new Error(gj.error || "Unable to load grading setup."); setSessions(sj.sessions || []); setSchemes(gj.schemes || []); if (!selected && gj.schemes?.[0]) setSelected(gj.schemes[0].id); } catch (e) { setError(e instanceof Error ? e.message : "Unable to load grading setup."); } }
  useEffect(() => { load(); }, [sessionId]);
  const active = schemes.find(x => x.id === selected) || schemes[0];
  async function save(body: Record<string, unknown>, success: string) { setError(""); setMessage(""); const r = await fetch("/api/grading", { method: "POST", headers: { "Content-Type": "application/json" }, body: JSON.stringify(body) }); const j = await r.json(); if (!r.ok) return setError(j.error || "Unable to save."); setMessage(success); await load(); return j; }

  return <main className="container"><header className="admissions-header"><div><div className="eyebrow">Aghaaz / Settings / Grading</div><h1>Grading Engine</h1><p>Define percentage bands once and let results use the configured grading scheme instead of hard-coded grade thresholds.</p></div><Link className="button secondary" href="/report-card-config">Report Card Setup</Link></header>
    {error && <div className="error" role="alert">{error}</div>}{message && <div className="success" role="status">{message}</div>}
    <section className="bottom-grid"><div className="panel"><div className="panel-heading"><div><h2>New grading scheme</h2><p>Leave academic year blank for a school-wide default.</p></div></div><label>Name<input className="input" value={name} onChange={e => setName(e.target.value)} placeholder="e.g. Primary Percentage" /></label><label>Academic year<select className="input" value={sessionId} onChange={e => setSessionId(e.target.value)}><option value="">School-wide default</option>{sessions.map(x => <option key={x.id} value={x.id}>{x.name}</option>)}</select></label><label>Description<textarea className="input" value={description} onChange={e => setDescription(e.target.value)} placeholder="How this scheme is used" /></label><button className="primary-button" disabled={!name.trim()} onClick={async () => { const r = await save({ action: "SCHEME", name, description, sessionId: sessionId || null }, "Grading scheme created."); if (r) { setName(""); setDescription(""); setSelected(r.id); } }}>Create scheme</button></div>
      <div className="panel"><div className="panel-heading"><div><h2>Add grading band</h2><p>{active ? `Adding to ${active.name}.` : "Create a scheme first."}</p></div></div><label>Scheme<select className="input" value={active?.id || ""} onChange={e => setSelected(e.target.value)}><option value="">Select scheme…</option>{schemes.map(x => <option key={x.id} value={x.id}>{x.name}{x.sessionId ? " · academic year" : " · default"}</option>)}</select></label><div className="form-grid"><label>Label<input className="input" value={label} onChange={e => setLabel(e.target.value)} placeholder="A+" /></label><label>Minimum %<input className="input" type="number" min="0" max="100" step="0.01" value={min} onChange={e => setMin(e.target.value)} /></label><label>Maximum %<input className="input" type="number" min="0" max="100" step="0.01" value={max} onChange={e => setMax(e.target.value)} /></label><label>Points<input className="input" type="number" min="0" step="0.01" value={points} onChange={e => setPoints(e.target.value)} placeholder="Optional" /></label></div><label className="checkbox-list"><span><input type="checkbox" checked={pass} onChange={e => setPass(e.target.checked)} /> Passing band</span></label><button className="primary-button" disabled={!active || !label.trim() || min === "" || max === ""} onClick={async () => { const r = await save({ action: "BAND", schemeId: active?.id, label, minPercentage: Number(min), maxPercentage: Number(max), points: points === "" ? null : Number(points), pass, displayOrder: active?.bands.length || 0 }, "Grading band added."); if (r) { setLabel(""); setMin(""); setMax(""); setPoints(""); } }}>Add band</button></div></section>
    <section className="applications-card"><div className="table-toolbar"><div><h2>Configured grading schemes</h2><p>Bands cannot overlap within a scheme. The default scheme is seeded with A+ through F.</p></div><button className="button" onClick={load}>Refresh</button></div>{schemes.length ? <div className="table-wrap"><table><thead><tr><th>Scheme</th><th>Scope</th><th>Band</th><th>Range</th><th>Points</th><th>Pass</th></tr></thead><tbody>{schemes.flatMap(s => s.bands.length ? s.bands.map(b => <tr key={b.id}><td><strong>{s.name}</strong></td><td>{s.sessionId ? (sessions.find(x => x.id === s.sessionId)?.name || "Academic year") : "School-wide default"}</td><td>{b.label}</td><td>{b.minPercentage}% – {b.maxPercentage}%</td><td>{b.points ?? "—"}</td><td>{b.pass ? "Yes" : "No"}</td></tr>) : [<tr key={s.id}><td><strong>{s.name}</strong></td><td>{s.sessionId ? "Academic year" : "School-wide default"}</td><td colSpan={4}>No bands configured</td></tr>])}</tbody></table></div> : <div className="empty-state">No grading schemes found.</div>}</section>
  </main>;
}
