"use client";

import Link from "next/link";
import { useEffect, useState } from "react";

type Student = {
  id: string; studentName?: string; dateOfBirth?: string | null; gender?: string | null; guardianName?: string; guardianPhone?: string; guardianEmail?: string | null; previousSchool?: string | null; desiredClass?: string; session?: { name?: string };
  enrollment?: { admissionNumber?: string; studentId?: string; className?: string; section?: string | null; enrolledAt?: string; status?: string; attendance?: Attendance[]; feeInvoices?: Invoice[]; results?: Result[]; leaveRequests?: Leave[]; homeworkSubmissions?: Submission[] } | null;
};
type Attendance = { id: string; date: string; status: string; remarks?: string | null };
type Invoice = { id: string; invoiceNumber: string; feeType: string; netAmount: string | number; dueDate: string; status: string; payments?: { amount: string | number; receiptNumber: string; paidAt: string }[] };
type Result = { id: string; marks: string | number; grade?: string | null; remarks?: string | null; paper: { subject: string; maxMarks: string | number; exam: { name: string } } };
type Leave = { id: string; startDate: string; endDate: string; reason: string; status: string; reviewRemarks?: string | null };
type Submission = { id: string; status: string; feedback?: string | null; homework: { title: string; subject: string; dueDate: string } };

function money(v: string | number) { return Number(v || 0).toLocaleString(); }
function date(v?: string | null) { return v ? new Date(v).toLocaleDateString() : "—"; }

export default function StudentProfilePage({ params }: { params: Promise<{ id: string }> }) {
  const [student, setStudent] = useState<Student | null>(null);
  const [user, setUser] = useState<{ role: string } | null>(null);
  const [loading, setLoading] = useState(true);
  const [error, setError] = useState("");
  const [editing, setEditing] = useState(false);
  const [saving, setSaving] = useState(false);
  const [form, setForm] = useState({ studentName: "", dateOfBirth: "", gender: "", guardianName: "", guardianPhone: "", guardianEmail: "", previousSchool: "" });

  useEffect(() => { (async () => { try { const { id } = await params; const [sr, ur] = await Promise.all([fetch(`/api/students/${id}`), fetch("/api/auth/me")]); const sd = await sr.json(); const ud = ur.ok ? await ur.json() : null; if (!sr.ok) throw Error(sd.error || "Unable to load student"); setStudent(sd); setUser(ud?.user || null); setForm({ studentName: sd.studentName || "", dateOfBirth: sd.dateOfBirth ? sd.dateOfBirth.slice(0,10) : "", gender: sd.gender || "", guardianName: sd.guardianName || "", guardianPhone: sd.guardianPhone || "", guardianEmail: sd.guardianEmail || "", previousSchool: sd.previousSchool || "" }); } catch (e) { setError(e instanceof Error ? e.message : "Unable to load student"); } finally { setLoading(false); } })(); }, [params]);

  async function save() { if (!student) return; setSaving(true); setError(""); try { const r = await fetch(`/api/students/${student.id}`, { method: "PATCH", headers: { "Content-Type": "application/json" }, body: JSON.stringify(form) }); const d = await r.json(); if (!r.ok) throw Error(d.error || "Unable to save"); setStudent({ ...student, ...d }); setEditing(false); } catch (e) { setError(e instanceof Error ? e.message : "Unable to save"); } finally { setSaving(false); } }

  if (loading) return <main className="container"><div className="empty-state">Loading student profile…</div></main>;
  if (!student) return <main className="container"><div className="error">{error || "Student not found"}</div></main>;
  const e = student.enrollment; const attendance = e?.attendance || []; const present = attendance.filter(x => x.status === "PRESENT" || x.status === "LATE").length; const invoices = e?.feeInvoices || []; const billed = invoices.reduce((s,x) => s + Number(x.netAmount), 0); const paid = invoices.flatMap(x => x.payments || []).reduce((s,x) => s + Number(x.amount), 0); const canEdit = user?.role === "SUPER_ADMIN" || user?.role === "ADMIN" || user?.role === "RECEPTIONIST";
  return <main className="container">
    <header className="admissions-header"><div><div className="eyebrow">Aghaaz School Management / Students</div><h1>{student.studentName}</h1><p>{e?.admissionNumber || "—"} · {e?.className || student.desiredClass || "—"}{e?.section ? ` · Section ${e.section}` : ""}</p></div><div className="toolbar-actions"><Link className="button secondary" href="/students">Back to Students</Link>{canEdit && <button className="button" onClick={() => setEditing(!editing)}>{editing ? "Cancel" : "Edit profile"}</button>}</div></header>
    {error && <div className="error">{error}</div>}
    {editing && <section className="applications-card"><div className="table-toolbar"><div><h2>Edit student & guardian</h2><p>Update the primary student record and guardian contact.</p></div></div><div className="form-grid">
      <label>Student name<input value={form.studentName} onChange={x=>setForm({...form,studentName:x.target.value})}/></label><label>Date of birth<input type="date" value={form.dateOfBirth} onChange={x=>setForm({...form,dateOfBirth:x.target.value})}/></label><label>Gender<select value={form.gender} onChange={x=>setForm({...form,gender:x.target.value})}><option value="">Not specified</option><option value="MALE">Male</option><option value="FEMALE">Female</option><option value="OTHER">Other</option></select></label><label>Previous school<input value={form.previousSchool} onChange={x=>setForm({...form,previousSchool:x.target.value})}/></label><label>Guardian name<input value={form.guardianName} onChange={x=>setForm({...form,guardianName:x.target.value})}/></label><label>Guardian phone<input value={form.guardianPhone} onChange={x=>setForm({...form,guardianPhone:x.target.value})}/></label><label>Guardian email<input type="email" value={form.guardianEmail} onChange={x=>setForm({...form,guardianEmail:x.target.value})}/></label>
    </div><button className="button" disabled={saving} onClick={save}>{saving ? "Saving…" : "Save changes"}</button></section>}
    <section className="admission-stats"><div className="admission-stat"><span>Attendance</span><strong>{attendance.length ? `${Math.round(present/attendance.length*100)}%` : "—"}</strong></div><div className="admission-stat"><span>Fees billed</span><strong>PKR {money(billed)}</strong></div><div className="admission-stat"><span>Fees paid</span><strong>PKR {money(paid)}</strong></div><div className="admission-stat"><span>Outstanding</span><strong>PKR {money(Math.max(0,billed-paid))}</strong></div></section>
    <section className="bottom-grid"><div className="panel"><div className="panel-heading"><div><h2>Student information</h2><p>Enrollment and personal record.</p></div></div><div className="detail-grid"><div><small>Student ID</small><strong>{e?.studentId || "—"}</strong></div><div><small>Admission No.</small><strong>{e?.admissionNumber || "—"}</strong></div><div><small>Date of birth</small><strong>{date(student.dateOfBirth)}</strong></div><div><small>Gender</small><strong>{student.gender || "—"}</strong></div><div><small>Session</small><strong>{student.session?.name || "—"}</strong></div><div><small>Enrolled</small><strong>{date(e?.enrolledAt)}</strong></div><div><small>Previous school</small><strong>{student.previousSchool || "—"}</strong></div><div><small>Status</small><strong>{e?.status || "active"}</strong></div></div></div><div className="panel"><div className="panel-heading"><div><h2>Primary guardian</h2><p>Current emergency/contact record.</p></div></div><div className="detail-grid"><div><small>Name</small><strong>{student.guardianName || "—"}</strong></div><div><small>Phone</small><strong>{student.guardianPhone || "—"}</strong></div><div><small>Email</small><strong>{student.guardianEmail || "—"}</strong></div></div></div></section>
    <section className="applications-card"><div className="table-toolbar"><div><h2>Attendance history</h2><p>Latest 100 attendance records.</p></div></div>{attendance.length ? <div className="table-wrap"><table><thead><tr><th>Date</th><th>Status</th><th>Remarks</th></tr></thead><tbody>{attendance.map(x=><tr key={x.id}><td>{date(x.date)}</td><td><span className="status-pill">{x.status}</span></td><td>{x.remarks || "—"}</td></tr>)}</tbody></table></div> : <div className="empty-state">No attendance records.</div>}</section>
    <section className="applications-card"><div className="table-toolbar"><div><h2>Fee history</h2><p>Invoices and recorded payments.</p></div></div>{invoices.length ? <div className="table-wrap"><table><thead><tr><th>Invoice</th><th>Type</th><th>Amount</th><th>Due</th><th>Status</th><th>Payments</th></tr></thead><tbody>{invoices.map(x=><tr key={x.id}><td>{x.invoiceNumber}</td><td>{x.feeType}</td><td>PKR {money(x.netAmount)}</td><td>{date(x.dueDate)}</td><td>{x.status}</td><td>{money((x.payments||[]).reduce((s,p)=>s+Number(p.amount),0))}</td></tr>)}</tbody></table></div> : <div className="empty-state">No fee invoices.</div>}</section>
    <section className="bottom-grid"><div className="panel"><div className="panel-heading"><div><h2>Results</h2><p>Recent academic performance.</p></div></div>{(e?.results||[]).length ? <div>{e!.results!.map(x=><div className="activity-row" key={x.id}><div><strong>{x.paper.subject} · {x.paper.exam.name}</strong><small>{x.marks}/{x.paper.maxMarks} · Grade {x.grade || "—"}</small></div></div>)}</div> : <div className="empty-state">No results recorded.</div>}</div><div className="panel"><div className="panel-heading"><div><h2>Leave</h2><p>Recent requests and decisions.</p></div></div>{(e?.leaveRequests||[]).length ? <div>{e!.leaveRequests!.map(x=><div className="activity-row" key={x.id}><div><strong>{date(x.startDate)} – {date(x.endDate)}</strong><small>{x.status} · {x.reason}</small></div></div>)}</div> : <div className="empty-state">No leave requests.</div>}</div></section>
    <section className="applications-card"><div className="table-toolbar"><div><h2>Homework</h2><p>Assignments and submission status.</p></div></div>{(e?.homeworkSubmissions||[]).length ? <div className="table-wrap"><table><thead><tr><th>Assignment</th><th>Subject</th><th>Due</th><th>Status</th><th>Feedback</th></tr></thead><tbody>{e!.homeworkSubmissions!.map(x=><tr key={x.id}><td>{x.homework.title}</td><td>{x.homework.subject}</td><td>{date(x.homework.dueDate)}</td><td>{x.status}</td><td>{x.feedback || "—"}</td></tr>)}</tbody></table></div> : <div className="empty-state">No homework submissions.</div>}</section>
  </main>;
}
