/* eslint-disable @typescript-eslint/no-explicit-any */
"use client";
import Link from "next/link";
import { useEffect, useMemo, useState } from "react";

type AcademicSession={id:string;name:string;startDate:string;endDate:string};
type Grade={id:string;name:string;code:string;sessionId:string};
type Section={id:string;name:string;gradeId:string;gradeName:string;capacity?:number|null};
type History={id:string;action:string;academicSessionName?:string|null;academicGradeName?:string|null;academicSectionName?:string|null;className:string;section?:string|null;status:string;effectiveAt:string;note?:string|null};
type S={id:string;studentName:string;dateOfBirth?:string|null;gender?:string|null;guardianName?:string;guardianPhone?:string;guardianEmail?:string|null;previousSchool?:string|null;session?:{name?:string};registry?:{grNumber:string}|null;customFields?:Record<string,string>;academic?:{academicSessionId?:string|null;academicSessionName?:string|null;academicGradeId?:string|null;academicGradeName?:string|null;academicSectionId?:string|null;academicSectionName?:string|null}|null;enrollmentHistory?:History[];enrollment?:{id?:string;studentId?:string;admissionNumber?:string;className?:string;section?:string|null;enrolledAt?:string;status?:string;attendance?:{id:string;date:string;status:string}[];feeInvoices?:{id:string;invoiceNumber:string;netAmount:string|number;status:string;dueDate:string;payments?:{amount:string|number}[]}[];results?:{id:string;marks:string|number;grade?:string|null;paper:{subject:string;maxMarks:string|number;exam:{name:string}}}[];homeworkSubmissions?:{id:string;status:string;homework:{title:string;subject:string;dueDate:string}}[]}};
const money=(v:any)=>Number(v||0).toLocaleString();
const date=(v?:string|null)=>v?new Date(v).toLocaleDateString():"—";
const statusLabel=(v?:string)=>v?v.replaceAll("_"," "):"—";

export default function Student360({params}:{params:Promise<{id:string}>}){
 const[s,setS]=useState<S|null>(null),[loading,setLoading]=useState(true),[error,setError]=useState(""),[sessions,setSessions]=useState<AcademicSession[]>([]),[grades,setGrades]=useState<Grade[]>([]),[sections,setSections]=useState<Section[]>([]),[action,setAction]=useState<"PROMOTE"|"TRANSFER"|"WITHDRAW"|"LEFT"|"EXPEL"|"REACTIVATE"|"READMIT"|null>(null),[sessionId,setSessionId]=useState(""),[gradeId,setGradeId]=useState(""),[sectionId,setSectionId]=useState(""),[note,setNote]=useState(""),[saving,setSaving]=useState(false),[actionError,setActionError]=useState(""),[readmitResult,setReadmitResult]=useState<{id:string;grNumber:string;admissionNumber:string}|null>(null);
 const load=async()=>{try{const{id}=await params;const[r,a]=await Promise.all([fetch(`/api/students/${id}`),fetch("/api/academic-structure")]);const[d,structure]=await Promise.all([r.json(),a.json()]);if(!r.ok)throw Error(d.error||"Unable to load student");setS(d);if(a.ok){setSessions(structure.sessions||[]);setGrades(structure.grades||[]);setSections(structure.sections||[]);}}catch(e){setError(e instanceof Error?e.message:"Unable to load student")}finally{setLoading(false)}};
 useEffect(()=>{load()},[params]);
 const currentGrades=useMemo(()=>grades.filter(g=>!sessionId||g.sessionId===sessionId),[grades,sessionId]);
 const currentSections=useMemo(()=>sections.filter(x=>x.gradeId===gradeId),[sections,gradeId]);
 async function lifecycle(){if(!s||!action)return;setSaving(true);setActionError("");try{const r=await fetch("/api/enrollment-actions",{method:"POST",headers:{"Content-Type":"application/json"},body:JSON.stringify({action,enrollmentId:e?.id,targetSessionId:action!=="WITHDRAW"?sessionId:undefined,targetGradeId:action!=="WITHDRAW"?gradeId:undefined,targetSectionId:action!=="WITHDRAW"?sectionId:undefined,note:note.trim()||undefined})});const d=await r.json();if(!r.ok)throw Error(d.error||"Unable to update enrollment");setAction(null);setNote("");if(d.newStudent)setReadmitResult({id:d.newStudent.id,grNumber:d.newStudent.grNumber,admissionNumber:d.newStudent.admissionNumber});await load()}catch(e){setActionError(e instanceof Error?e.message:"Unable to update enrollment")}finally{setSaving(false)}}
 if(loading)return <main className="container"><div className="empty-state">Loading Student 360…</div></main>;
 if(!s)return <main className="container"><div className="error">{error||"Student not found"}</div></main>;
 const e=s.enrollment;const a=e?.attendance||[];const present=a.filter(x=>x.status==="PRESENT"||x.status==="LATE").length;const invoices=e?.feeInvoices||[];const billed=invoices.reduce((n,x)=>n+Number(x.netAmount),0);const paid=invoices.flatMap(x=>x.payments||[]).reduce((n,x)=>n+Number(x.amount),0);const activeStatus=!['WITHDRAWN','TRANSFERRED','INACTIVE','withdrawn','transferred','inactive'].includes(e?.status||"");
 return <main className="container">
  <header className="admissions-header"><div><div className="eyebrow">Students / Student 360</div><h1>{s.studentName}</h1><p><strong>{s.registry?.grNumber||"GR not assigned"}</strong> · {e?.className||"—"}{e?.section?` · Section ${e.section}`:""} · <span className="status-pill">{statusLabel(e?.status||"ACTIVE")}</span></p></div><div className="toolbar-actions"><Link className="button secondary" href="/students">Students</Link><button className="button secondary" onClick={()=>window.print()}>Print</button></div></header>
  <section className="admission-stats"><div className="admission-stat"><span>GR Number (current enrollment)</span><strong>{s.registry?.grNumber||"—"}</strong></div><div className="admission-stat"><span>Attendance</span><strong>{a.length?`${Math.round(present/a.length*100)}%`:"—"}</strong></div><div className="admission-stat"><span>Fees paid</span><strong>PKR {money(paid)}</strong></div><div className="admission-stat"><span>Outstanding</span><strong>PKR {money(Math.max(0,billed-paid))}</strong></div></section>
  <section className="applications-card"><div className="table-toolbar"><div><h2>Enrollment lifecycle</h2><p>Promotions and transfers keep the current GR. A student marked Left or Expelled receives a new GR when re-admitted.</p></div><div className="toolbar-actions">{activeStatus&&<><button className="button" onClick={()=>setAction("PROMOTE")}>Promote</button><button className="button secondary" onClick={()=>setAction("TRANSFER")}>Transfer</button><button className="button secondary" onClick={()=>setAction("LEFT")}>Mark Left</button><button className="button secondary" onClick={()=>setAction("EXPEL")}>Expel</button></>}{!activeStatus&&["LEFT","EXPELLED","WITHDRAWN"].includes((e?.status||"").toUpperCase())&&<button className="button" onClick={()=>setAction("READMIT")}>Re-admit with new GR</button>}{!activeStatus&&["INACTIVE","TRANSFERRED"].includes((e?.status||"").toUpperCase())&&<button className="button" onClick={()=>setAction("REACTIVATE")}>Reactivate</button>}</div></div>
   <div className="detail-grid"><div><small>Academic year</small><strong>{s.academic?.academicSessionName||s.session?.name||"—"}</strong></div><div><small>Grade</small><strong>{s.academic?.academicGradeName||e?.className||"—"}</strong></div><div><small>Section</small><strong>{s.academic?.academicSectionName||e?.section||"—"}</strong></div><div><small>Enrollment status</small><strong>{statusLabel(e?.status||"ACTIVE")}</strong></div></div>
   {action&&action!=="WITHDRAW"&&action!=="LEFT"&&action!=="EXPEL"&&<div style={{marginTop:24}}><div className="form-grid"><label>Academic year *<select value={sessionId} onChange={x=>{setSessionId(x.target.value);setGradeId("");setSectionId("")}}><option value="">Select</option>{sessions.map(x=><option key={x.id} value={x.id}>{x.name}</option>)}</select></label><label>Grade *<select value={gradeId} onChange={x=>{setGradeId(x.target.value);setSectionId("")}}><option value="">Select</option>{currentGrades.map(x=><option key={x.id} value={x.id}>{x.name} ({x.code})</option>)}</select></label><label>Section *<select value={sectionId} onChange={x=>setSectionId(x.target.value)}><option value="">Select</option>{currentSections.map(x=><option key={x.id} value={x.id}>{x.name}{x.capacity?` · capacity ${x.capacity}`:""}</option>)}</select></label></div><label style={{display:"block",marginTop:16}}>Note<textarea value={note} onChange={x=>setNote(x.target.value)} placeholder={action==="TRANSFER"?"Optional transfer details":action==="READMIT"?"Optional re-admission note":"Optional promotion note"}/></label></div>}
   {action&&(action==="WITHDRAW"||action==="LEFT"||action==="EXPEL"||action==="REACTIVATE")&&<label style={{display:"block",marginTop:16}}>Note<textarea value={note} onChange={x=>setNote(x.target.value)} placeholder={action==="EXPEL"?"Reason for expulsion":action==="LEFT"?"Leaving / departure note":"Optional lifecycle note"}/></label>}
   {actionError&&<div className="error" style={{marginTop:16}}>{actionError}</div>}
   {action&&<div className="toolbar-actions" style={{marginTop:20}}><button className="button secondary" onClick={()=>{setAction(null);setActionError("")}}>Cancel</button><button className="button" disabled={saving||(action!=="WITHDRAW"&&action!=="LEFT"&&action!=="EXPEL"&&(!sessionId||!gradeId||!sectionId))} onClick={lifecycle}>{saving?"Saving…":`Confirm ${statusLabel(action)}`}</button></div>}
  {readmitResult&&<section className="applications-card"><div className="status-card"><strong>Re-admission created.</strong><p style={{margin:"8px 0"}}>This student has a new enrollment and a new GR number. The previous Left/Expelled record remains unchanged.</p><div className="detail-grid"><div><small>New GR Number</small><strong>{readmitResult.grNumber}</strong></div><div><small>New Admission Number</small><strong>{readmitResult.admissionNumber}</strong></div></div><div className="toolbar-actions" style={{marginTop:16}}><Link className="button" href={`/students/${readmitResult.id}`}>Open New Student Record</Link><button className="button secondary" onClick={()=>setReadmitResult(null)}>Dismiss</button></div></div></section>}
  </section>
  <section className="applications-card"><div className="table-toolbar"><div><h2>Enrollment history</h2><p>Lifecycle events are retained for the General Register and audit trail.</p></div></div>{s.enrollmentHistory?.length?<div className="table-wrap"><table><thead><tr><th>Date</th><th>Action</th><th>Academic year</th><th>Grade / Section</th><th>Status</th><th>Note</th></tr></thead><tbody>{s.enrollmentHistory.map(x=><tr key={x.id}><td>{date(x.effectiveAt)}</td><td>{statusLabel(x.action)}</td><td>{x.academicSessionName||"—"}</td><td>{x.academicGradeName||x.className}{x.academicSectionName||x.section?` · ${x.academicSectionName||x.section}`:""}</td><td>{statusLabel(x.status)}</td><td>{x.note||"—"}</td></tr>)}</tbody></table></div>:<div className="empty-state">No lifecycle changes recorded yet.</div>}</section>
  <section className="bottom-grid"><div className="panel"><div className="panel-heading"><div><h2>Overview</h2><p>Permanent identity and current enrollment.</p></div></div><div className="detail-grid"><div><small>GR Number</small><strong>{s.registry?.grNumber||"—"}</strong></div><div><small>Student ID</small><strong>{e?.studentId||"—"}</strong></div><div><small>Admission Number</small><strong>{e?.admissionNumber||"—"}</strong></div><div><small>Date of birth</small><strong>{date(s.dateOfBirth)}</strong></div><div><small>Gender</small><strong>{s.gender||"—"}</strong></div><div><small>Session</small><strong>{s.session?.name||"—"}</strong></div><div><small>Class</small><strong>{e?.className||"—"}</strong></div><div><small>Enrolled</small><strong>{date(e?.enrolledAt)}</strong></div></div></div><div className="panel"><div className="panel-heading"><div><h2>Guardian</h2><p>Primary contact information.</p></div></div><div className="detail-grid"><div><small>Name</small><strong>{s.guardianName||"—"}</strong></div><div><small>Phone</small><strong>{s.guardianPhone||"—"}</strong></div><div><small>Email</small><strong>{s.guardianEmail||"—"}</strong></div><div><small>Previous school</small><strong>{s.previousSchool||"—"}</strong></div></div></div></section>
  <section className="applications-card"><div className="table-toolbar"><div><h2>Additional Information</h2><p>School-defined fields saved with this student.</p></div></div>{s.customFields&&Object.keys(s.customFields).length?<div className="detail-grid">{Object.entries(s.customFields).map(([k,v])=><div key={k}><small>{k.replaceAll("_"," ")}</small><strong>{v||"—"}</strong></div>)}</div>:<div className="empty-state">No additional fields recorded.</div>}</section>
  <section className="bottom-grid"><div className="panel"><div className="panel-heading"><div><h2>Attendance</h2><p>Recent attendance records.</p></div></div>{a.length?<div className="table-wrap"><table><thead><tr><th>Date</th><th>Status</th></tr></thead><tbody>{a.slice(0,20).map(x=><tr key={x.id}><td>{date(x.date)}</td><td>{x.status}</td></tr>)}</tbody></table></div>:<div className="empty-state">No attendance records.</div>}</div><div className="panel"><div className="panel-heading"><div><h2>Fees</h2><p>Current invoices and collections.</p></div></div>{invoices.length?<div className="table-wrap"><table><thead><tr><th>Invoice</th><th>Amount</th><th>Status</th></tr></thead><tbody>{invoices.slice(0,10).map(x=><tr key={x.id}><td>{x.invoiceNumber}</td><td>PKR {money(x.netAmount)}</td><td>{x.status}</td></tr>)}</tbody></table></div>:<div className="empty-state">No fee invoices.</div>}</div></section>
  <section className="bottom-grid"><div className="panel"><div className="panel-heading"><div><h2>Homework</h2><p>Submission status.</p></div></div>{(e?.homeworkSubmissions||[]).length?<div>{e!.homeworkSubmissions!.slice(0,10).map(x=><div className="activity-row" key={x.id}><div><strong>{x.homework.title}</strong><small>{x.homework.subject} · {x.status} · Due {date(x.homework.dueDate)}</small></div></div>)}</div>:<div className="empty-state">No homework submissions.</div>}</div><div className="panel"><div className="panel-heading"><div><h2>Academics</h2><p>Recent results.</p></div></div>{(e?.results||[]).length?<div>{e!.results!.slice(0,10).map(x=><div className="activity-row" key={x.id}><div><strong>{x.paper.subject} · {x.paper.exam.name}</strong><small>{x.marks}/{x.paper.maxMarks} · Grade {x.grade||"—"}</small></div></div>)}</div>:<div className="empty-state">No results recorded.</div>}</div></section>
 </main>;
}
