"use client";
import { useEffect, useState } from "react";

type Band={id:string;label:string;minPercentage:number;maxPercentage:number;points:number|null;pass:boolean;displayOrder:number};
type Scheme={id:string;sessionId:string|null;name:string;description:string|null;active:boolean;bands:Band[]};
type Session={id:string;name:string};
export default function GradingPage(){
 const [schemes,setSchemes]=useState<Scheme[]>([]),[sessions,setSessions]=useState<Session[]>([]),[sessionId,setSessionId]=useState(""),[error,setError]=useState(""),[saved,setSaved]=useState("");
 const [scheme,setScheme]=useState({name:"",description:"",sessionId:""}); const [band,setBand]=useState({schemeId:"",label:"",minPercentage:"",maxPercentage:"",points:"",pass:true,displayOrder:"0"});
 async function load(){const [g,s]=await Promise.all([fetch(`/api/grading${sessionId?`?sessionId=${encodeURIComponent(sessionId)}`:""}`),fetch('/api/academic-sessions')]);const gd=await g.json(),sd=await s.json();if(!g.ok)throw new Error(gd.error||'Unable to load grading');setSchemes(gd.schemes||[]);const list=Array.isArray(sd)?sd:sd.sessions||[];setSessions(list);}
 useEffect(()=>{load().catch(e=>setError(e.message))},[sessionId]);
 async function post(body:Record<string,unknown>){setError("");setSaved("");const r=await fetch('/api/grading',{method:'POST',headers:{'Content-Type':'application/json'},body:JSON.stringify(body)});const v=await r.json();if(!r.ok)throw new Error(v.error||'Unable to save');setSaved('Saved successfully.');await load()}
 return <main className="container"><header className="admissions-header"><div><div className="eyebrow">Aghaaz / Academic Settings</div><h1>Grading Engine</h1><p>Configure percentage bands and grade points by academic session.</p></div></header>{error&&<div className="alert error">{error}</div>}{saved&&<div className="alert success">{saved}</div>}
 <section className="module-grid">
  <form className="module-card" onSubmit={async e=>{e.preventDefault();try{await post({action:'SCHEME',...scheme});setScheme({name:'',description:'',sessionId:''})}catch(x){setError(x instanceof Error?x.message:'Unable to save')}}}><h3>New grading scheme</h3><label className="field"><span>Name</span><input value={scheme.name} onChange={e=>setScheme({...scheme,name:e.target.value})} placeholder="Primary Percentage Scheme" required/></label><label className="field"><span>Academic session (optional)</span><select value={scheme.sessionId} onChange={e=>setScheme({...scheme,sessionId:e.target.value})}><option value="">All sessions</option>{sessions.map(s=><option key={s.id} value={s.id}>{s.name}</option>)}</select></label><label className="field"><span>Description</span><textarea value={scheme.description} onChange={e=>setScheme({...scheme,description:e.target.value})}/></label><button className="button">Create scheme</button></form>
  <form className="module-card" onSubmit={async e=>{e.preventDefault();try{await post({action:'BAND',...band,minPercentage:Number(band.minPercentage),maxPercentage:Number(band.maxPercentage),points:band.points===''?null:Number(band.points),displayOrder:Number(band.displayOrder)});setBand({...band,label:'',minPercentage:'',maxPercentage:'',points:''})}catch(x){setError(x instanceof Error?x.message:'Unable to save')}}}><h3>Add grading band</h3><label className="field"><span>Scheme</span><select value={band.schemeId} onChange={e=>setBand({...band,schemeId:e.target.value})} required><option value="">Select scheme</option>{schemes.map(s=><option key={s.id} value={s.id}>{s.name}</option>)}</select></label><label className="field"><span>Label</span><input value={band.label} onChange={e=>setBand({...band,label:e.target.value})} placeholder="A+" required/></label><div className="form-grid"><label>Min %<input className="input" type="number" min="0" max="100" step="0.01" value={band.minPercentage} onChange={e=>setBand({...band,minPercentage:e.target.value})} required/></label><label>Max %<input className="input" type="number" min="0" max="100" step="0.01" value={band.maxPercentage} onChange={e=>setBand({...band,maxPercentage:e.target.value})} required/></label></div><div className="form-grid"><label>Points<input className="input" type="number" min="0" step="0.01" value={band.points} onChange={e=>setBand({...band,points:e.target.value})}/></label><label>Order<input className="input" type="number" min="0" step="1" value={band.displayOrder} onChange={e=>setBand({...band,displayOrder:e.target.value})}/></label></div><label className="field"><span><input type="checkbox" checked={band.pass} onChange={e=>setBand({...band,pass:e.target.checked})}/> Passing band</span></label><button className="button">Add band</button></form>
 </section>
 <section className="applications-card"><div className="form-grid"><label>Filter session<select className="input" value={sessionId} onChange={e=>setSessionId(e.target.value)}><option value="">All sessions</option>{sessions.map(s=><option key={s.id} value={s.id}>{s.name}</option>)}</select></label></div></section>
 <section className="module-grid">{schemes.map(s=><div className="module-card" key={s.id}><h3>{s.name}</h3><p>{s.description||'No description'}{s.sessionId?' · Session-specific':' · Global'}</p>{s.bands.length?<div className="table-wrap"><table><thead><tr><th>Label</th><th>Range</th><th>Points</th><th>Status</th></tr></thead><tbody>{s.bands.map(b=><tr key={b.id}><td><strong>{b.label}</strong></td><td>{b.minPercentage}–{b.maxPercentage}%</td><td>{b.points??'—'}</td><td>{b.pass?'Pass':'Fail'}</td></tr>)}</tbody></table></div>:<p>No bands configured.</p>}</div>)}</section>
 </main>
}
