import { NextRequest, NextResponse } from "next/server";
import { prisma } from "@/lib/prisma";
import { getCurrentUser, roleAllowed } from "@/lib/auth";
const ROLES = ["SUPER_ADMIN","ADMIN","TEACHER","ACCOUNTANT","RECEPTIONIST"] as const;
export async function GET() {
  try {
    const user=await getCurrentUser();
    if(!user)return NextResponse.json({error:"Authentication required."},{status:401});
    if(!roleAllowed(user.role,[...ROLES]))return NextResponse.json({error:"You do not have permission to access Student Intelligence."},{status:403});
    const now=new Date(), attendanceStart=new Date(now.getTime()-30*86400000), monthStart=new Date(now.getFullYear(),now.getMonth(),1);
    type StudentSignalRow = { enrollmentId:string; studentName:string; admissionNumber:string; grNumber:string|null; gradeName:string|null; sectionName:string|null; attendanceTotal:number; attendancePresent:number; overdueFees:number; overdueAmount:string; failingResults:number; openBehaviour:number; highBehaviour:number };
    const rows=await prisma.$queryRawUnsafe<StudentSignalRow[]>(`SELECT e."id" AS "enrollmentId",a."studentName",e."admissionNumber",sr."grNumber",g."name" AS "gradeName",sec."name" AS "sectionName",COALESCE(att."attendanceTotal",0)::int AS "attendanceTotal",COALESCE(att."attendancePresent",0)::int AS "attendancePresent",COALESCE(fee."overdueFees",0)::int AS "overdueFees",COALESCE(fee."overdueAmount",0)::text AS "overdueAmount",COALESCE(res."failingResults",0)::int AS "failingResults",COALESCE(beh."openBehaviour",0)::int AS "openBehaviour",COALESCE(beh."highBehaviour",0)::int AS "highBehaviour" FROM "Enrollment" e JOIN "Application" a ON a."id"=e."applicationId" LEFT JOIN "StudentRegistry" sr ON sr."enrollmentId"=e."id" LEFT JOIN "AcademicGrade" g ON g."id"=e."academicGradeId" LEFT JOIN "AcademicSection" sec ON sec."id"=e."academicSectionId" LEFT JOIN (SELECT "studentId",COUNT(*) AS "attendanceTotal",COUNT(*) FILTER (WHERE "status" IN ('PRESENT','LATE')) AS "attendancePresent" FROM "Attendance" WHERE "date">=$1 GROUP BY "studentId") att ON att."studentId"=e."id" LEFT JOIN (SELECT "studentId",COUNT(*) FILTER (WHERE "status" NOT IN ('PAID','CANCELLED')) AS "overdueFees",COALESCE(SUM("netAmount") FILTER (WHERE "status" NOT IN ('PAID','CANCELLED')),0) AS "overdueAmount" FROM "FeeInvoice" WHERE "dueDate"<$2 GROUP BY "studentId") fee ON fee."studentId"=e."id" LEFT JOIN (SELECT r."studentId",COUNT(*) AS "failingResults" FROM "Result" r JOIN "ExamPaper" p ON p."id"=r."paperId" WHERE r."createdAt">=$3 AND r."marks"<p."passMarks" GROUP BY r."studentId") res ON res."studentId"=e."id" LEFT JOIN (SELECT "enrollmentId",COUNT(*) FILTER (WHERE "status" IN ('OPEN','IN_PROGRESS')) AS "openBehaviour",COUNT(*) FILTER (WHERE "status" IN ('OPEN','IN_PROGRESS') AND "severity" IN ('HIGH','CRITICAL')) AS "highBehaviour" FROM "StudentBehaviourRecord" GROUP BY "enrollmentId") beh ON beh."enrollmentId"=e."id" WHERE e."status" IN ('active','ACTIVE','enrolled','ENROLLED') ORDER BY a."studentName" ASC LIMIT 1000`,attendanceStart,now,monthStart);
    const students=rows.map(row=>{const total=Number(row.attendanceTotal),present=Number(row.attendancePresent);const attendancePercent=total?Number(((present/total)*100).toFixed(1)):null;const signals={attendance:attendancePercent!==null&&total>=5&&attendancePercent<80,fees:Number(row.overdueFees)>0,academic:Number(row.failingResults)>0,wellbeing:Number(row.openBehaviour)>0,highWellbeing:Number(row.highBehaviour)>0};const score=(signals.attendance?2:0)+(signals.fees?2:0)+(signals.academic?2:0)+(signals.wellbeing?1:0)+(signals.highWellbeing?2:0);return {...row,attendanceTotal:total,attendancePercent,overdueFees:Number(row.overdueFees),overdueAmount:Number(row.overdueAmount),failingResults:Number(row.failingResults),openBehaviour:Number(row.openBehaviour),highBehaviour:Number(row.highBehaviour),score,signals}}).filter(row=>row.score>0).sort((a,b)=>b.score-a.score||a.studentName.localeCompare(b.studentName));
    return NextResponse.json({generatedAt:now.toISOString(),windowDays:30,students});
  } catch(error){console.error(error);return NextResponse.json({error:"Unable to load Student Intelligence signals. Check the latest database migrations."},{status:500});}
}