import { NextRequest, NextResponse } from "next/server";
import { prisma } from "@/lib/prisma";
import { getCurrentUser, roleAllowed } from "@/lib/auth";
import { getCustomFieldDefinitions } from "@/lib/student-registry";
import { getTeacherSectionIds } from "@/lib/student-access";
import type { Gender, UserRole } from "@prisma/client";
const VIEW_ROLES:UserRole[]=["SUPER_ADMIN","ADMIN","TEACHER","ACCOUNTANT","RECEPTIONIST"]; const EDIT_ROLES:UserRole[]=["SUPER_ADMIN","ADMIN","RECEPTIONIST"];
type RegistryRow = { id: string; grNumber: string | null };
type CustomValueRow = { fieldId: string; value: string | null };
type AcademicRow = { academicSessionId: string | null; academicSessionName: string | null; academicGradeId: string | null; academicGradeName: string | null; academicSectionId: string | null; academicSectionName: string | null };
type HistoryRow = { id: string; action: string; academicSessionId: string | null; academicSessionName: string | null; academicGradeId: string | null; academicGradeName: string | null; academicSectionId: string | null; academicSectionName: string | null; className: string | null; section: string | null; status: string; effectiveAt: Date; note: string | null };
export async function GET(_request:NextRequest,{params}:{params:Promise<{id:string}>}){const user=await getCurrentUser();if(!user)return NextResponse.json({error:"Unauthorized"},{status:401});if(!roleAllowed(user.role,VIEW_ROLES))return NextResponse.json({error:"Forbidden"},{status:403});const{id}=await params;try{const teacherSectionIds=user.role === "TEACHER" ? await getTeacherSectionIds(user.id) : null;if (teacherSectionIds?.length === 0) return NextResponse.json({error:"Student not found"},{status:404});const student=await prisma.application.findFirst({where:{id,enrollment:{is:{...(teacherSectionIds ? {academicSectionId:{in:teacherSectionIds}} : {})}}},include:{session:true,enrollment:{include:{attendance:{orderBy:{date:"desc"},take:100},feeInvoices:{include:{payments:{orderBy:{paidAt:"desc"}}},orderBy:{dueDate:"desc"},take:100},results:{include:{paper:{include:{exam:true}}},orderBy:{createdAt:"desc"},take:100},leaveRequests:{orderBy:{startDate:"desc"},take:50},homeworkSubmissions:{include:{homework:true},orderBy:{updatedAt:"desc"},take:100}}}}});if(!student)return NextResponse.json({error:"Student not found"},{status:404});const reg=await prisma.$queryRawUnsafe<RegistryRow[]>(`SELECT "id","grNumber" FROM "StudentRegistry" WHERE "enrollmentId"=$1 LIMIT 1`,student.enrollment!.id);const defs=await getCustomFieldDefinitions();const values=reg[0]?await prisma.$queryRawUnsafe<CustomValueRow[]>(`SELECT "fieldId","value" FROM "StudentCustomFieldValue" WHERE "studentRegistryId"=$1`,reg[0].id):[];const valueMap=Object.fromEntries(values.map(v=>{const d=defs.find(x=>x.id===v.fieldId);return[d?.key||v.fieldId,v.value]}));const academic=await prisma.$queryRawUnsafe<AcademicRow[]>(`SELECT e."academicSessionId",a."name" AS "academicSessionName",e."academicGradeId",g."name" AS "academicGradeName",e."academicSectionId",s."name" AS "academicSectionName" FROM "Enrollment" e LEFT JOIN "AcademicSession" a ON a."id"=e."academicSessionId" LEFT JOIN "AcademicGrade" g ON g."id"=e."academicGradeId" LEFT JOIN "AcademicSection" s ON s."id"=e."academicSectionId" WHERE e."id"=$1 LIMIT 1`,student.enrollment!.id);const history=await prisma.$queryRawUnsafe<HistoryRow[]>(`SELECT "id","action","academicSessionId","academicSessionName","academicGradeId","academicGradeName","academicSectionId","academicSectionName","className","section","status","effectiveAt","note" FROM "EnrollmentHistory" WHERE "enrollmentId"=$1 ORDER BY "effectiveAt" DESC,"createdAt" DESC`,student.enrollment!.id);return NextResponse.json({...student,registry:reg[0]||null,customFields:valueMap,academic:academic[0]||null,enrollmentHistory:history});}catch(error){console.error(error);return NextResponse.json({error:"Unable to load student profile."},{status:500})}}
export async function PATCH(request:NextRequest,{params}:{params:Promise<{id:string}>}){const user=await getCurrentUser();if(!user)return NextResponse.json({error:"Unauthorized"},{status:401});if(!roleAllowed(user.role,EDIT_ROLES))return NextResponse.json({error:"Forbidden"},{status:403});const{id}=await params;try{const body=await request.json() as Record<string,unknown>;const studentName=typeof body.studentName==="string"?body.studentName.trim():"",guardianName=typeof body.guardianName==="string"?body.guardianName.trim():"",guardianPhone=typeof body.guardianPhone==="string"?body.guardianPhone.trim():"";if(!studentName||!guardianName||!guardianPhone)return NextResponse.json({error:"Student name, guardian name and guardian phone are required."},{status:400});const dateOfBirth=typeof body.dateOfBirth==="string"&&body.dateOfBirth?new Date(body.dateOfBirth):null;if(dateOfBirth&&Number.isNaN(dateOfBirth.getTime()))return NextResponse.json({error:"Invalid date of birth."},{status:400});const gender=typeof body.gender==="string"&&["MALE","FEMALE","OTHER"].includes(body.gender)?body.gender as Gender:null;const guardianEmail=typeof body.guardianEmail==="string"?body.guardianEmail.trim()||null:null;const previousSchool=typeof body.previousSchool==="string"?body.previousSchool.trim()||null:null;const existing=await prisma.application.findFirst({where:{id,enrollment:{isNot:null}},select:{id:true}});if(!existing)return NextResponse.json({error:"Student not found"},{status:404});const updated=await prisma.application.update({where:{id},data:{studentName,dateOfBirth,gender,guardianName,guardianPhone,guardianEmail,previousSchool},include:{session:true,enrollment:true}});return NextResponse.json(updated);}catch(error){console.error(error);return NextResponse.json({error:"Unable to update student profile."},{status:500})}}
