"use client";
import { useEffect, useState } from "react";

type Homework={id:string;title:string;description:string;className:string;section?:string|null;subject:string;teacher:string;assignedDate:string;dueDate:string;status:string;_count:{submissions:number}};
const initial={title:"",description:"",className:"",section:"",subject:"",teacher:"",assignedDate:new Date().toISOString().slice(0,10),dueDate:"",status:"PUBLISHED"};

export default function HomeworkPage(){
 const [items,setItems]=useState<Homework[]>([]); const [loading,setLoading]=useState(true); const [saving,setSaving]=useState(false); const [error,setError]=useState(""); const [filter,setFilter]=useState(""); const [form,setForm]=useState(initial);
 const load=()=>{setLoading(true);const q=filter?`?class=${encodeURIComponent(filter)}`:"";fetch(`/api/homework${q}`).then(async r=>{const d=await r.json();if(!r.ok)throw new Error(d.error||"Unable to load homework");return d}).then(setItems).catch(e=>setError(e.message)).finally(()=>setLoading(false));};
 useEffect(()=>{load()},[filter]);
 async function create(e:React.FormEvent){e.preventDefault();setSaving(true);setError("");try{const r=await fetch("/api/homework",{method:"POST",headers:{"Content-Type":"application/json"},body:JSON.stringify(form)});const d=await r.json();if(!r.ok)throw new Error(d.error||"Unable to create homework");setForm({...initial,assignedDate:new Date().toISOString().slice(0,10)});load()}catch(e){setError(e instanceof Error?e.message:"Unable to save homework")}finally{setSaving(false)}}
 async function close(id:string){const r=await fetch(`/api/homework?id=${id}`,{method:"PATCH",headers:{"Content-Type":"application/json"},body:JSON.stringify({status:"CLOSED"})});if(!r.ok){const d=await r.json();setError(d.error||"Unable to update homework");return}load()}
 async function remove(id:string){if(!confirm("Delete this homework assignment?"))return;const r=await fetch(`/api/homework?id=${id}`,{method:"DELETE"});if(!r.ok){const d=await r.json();setError(d.error||"Unable to delete homework");return}setItems(x=>x.filter(i=>i.id!==id))}
 return <main className="admissions-shell"><header className="admissions-header"><div><div className="eyebrow">Aghaaz School Management / Homework</div><h1>Homework</h1><p>Create assignments, track due dates and manage their lifecycle.</p></div></header>{error&&<div className="error">{error}</div>}
 <section className="form-card"><h2>Create assignment</h2><form className="form-grid" onSubmit={create}><label>Title<input className="input" required value={form.title} onChange={e=>setForm({...form,title:e.target.value})} placeholder="Chapter 4 exercises"/></label><label>Subject<input className="input" required value={form.subject} onChange={e=>setForm({...form,subject:e.target.value})} placeholder="Mathematics"/></label><label>Class<input className="input" required value={form.className} onChange={e=>setForm({...form,className:e.target.value})} placeholder="Grade 5"/></label><label>Section<input className="input" value={form.section} onChange={e=>setForm({...form,section:e.target.value})} placeholder="A"/></label><label>Teacher<input className="input" required value={form.teacher} onChange={e=>setForm({...form,teacher:e.target.value})} placeholder="Teacher name"/></label><label>Assigned date<input className="input" required type="date" value={form.assignedDate} onChange={e=>setForm({...form,assignedDate:e.target.value})}/></label><label>Due date<input className="input" required type="date" value={form.dueDate} onChange={e=>setForm({...form,dueDate:e.target.value})}/></label><label>Status<select className="input" value={form.status} onChange={e=>setForm({...form,status:e.target.value})}><option>PUBLISHED</option><option>DRAFT</option><option>CLOSED</option></select></label><label className="full-field">Description<textarea className="input" required rows={4} value={form.description} onChange={e=>setForm({...form,description:e.target.value})} placeholder="Instructions for students…"/></label><div><button className="button" disabled={saving}>{saving?"Saving…":"Create Assignment"}</button></div></form></section>
 <section className="applications-card"><div className="table-toolbar"><div><h2>Assignments</h2><p>{items.length} assignment{items.length===1?"":"s"}</p></div><input className="input toolbar-search" value={filter} onChange={e=>setFilter(e.target.value)} placeholder="Filter by class…"/></div>{loading?<div className="empty-state">Loading homework…</div>:items.length===0?<div className="empty-state"><strong>No assignments yet</strong><span>Create the first assignment above.</span></div>:<div className="table-wrap"><table><thead><tr><th>Assignment</th><th>Class</th><th>Subject</th><th>Teacher</th><th>Due</th><th>Status</th><th>Submissions</th><th></th></tr></thead><tbody>{items.map(x=><tr key={x.id}><td><strong>{x.title}</strong><small>{x.description}</small></td><td>{x.className}{x.section?` / ${x.section}`:""}</td><td>{x.subject}</td><td>{x.teacher}</td><td>{new Date(x.dueDate).toLocaleDateString()}</td><td><span className={`status-pill status-${x.status.toLowerCase()}`}>{x.status}</span></td><td>{x._count.submissions}</td><td><button className="row-action" onClick={()=>close(x.id)} disabled={x.status==="CLOSED"}>Close</button> <button className="row-action" onClick={()=>remove(x.id)}>Delete</button></td></tr>)}</tbody></table></div>}</section></main>
}
