"use client";

import Link from "next/link";
import { FormEvent, useEffect, useMemo, useState } from "react";

type EventItem = { id: string; title: string; description: string | null; eventType: string; audience: string; startDate: string; endDate: string; allDay: boolean; location: string | null; status: string };
const TYPES = ["GENERAL", "HOLIDAY", "EXAM", "PARENT_MEETING", "STAFF_MEETING", "DEADLINE", "ACTIVITY", "OTHER"];
const AUDIENCES = ["ALL", "STAFF", "TEACHERS", "PARENTS", "STUDENTS"];
const dateInput = (date = new Date()) => new Date(date.getTime() - date.getTimezoneOffset() * 60000).toISOString().slice(0, 16);

export default function CalendarPage() {
  const [events, setEvents] = useState<EventItem[]>([]); const [title, setTitle] = useState(""); const [description, setDescription] = useState("");
  const [eventType, setEventType] = useState("GENERAL"); const [audience, setAudience] = useState("ALL"); const [startDate, setStartDate] = useState(dateInput()); const [endDate, setEndDate] = useState(dateInput(new Date(Date.now() + 60 * 60 * 1000)));
  const [allDay, setAllDay] = useState(false); const [location, setLocation] = useState(""); const [status, setStatus] = useState("PUBLISHED"); const [error, setError] = useState(""); const [message, setMessage] = useState(""); const [loading, setLoading] = useState(true); const [saving, setSaving] = useState(false);

  async function load() { setLoading(true); try { const from = new Date(); from.setHours(0,0,0,0); const to = new Date(from); to.setDate(to.getDate() + 120); const response = await fetch(`/api/calendar?from=${encodeURIComponent(from.toISOString())}&to=${encodeURIComponent(to.toISOString())}`); const data = await response.json(); if (!response.ok) throw new Error(data.error || "Unable to load calendar."); setEvents(data.events || []); } catch (e) { setError(e instanceof Error ? e.message : "Unable to load calendar."); } finally { setLoading(false); } }
  useEffect(() => { void load(); }, []);

  const grouped = useMemo(() => { const map = new Map<string, EventItem[]>(); for (const event of events) { const key = new Date(event.startDate).toLocaleDateString(undefined, { weekday: "long", year: "numeric", month: "long", day: "numeric" }); const list = map.get(key) || []; list.push(event); map.set(key, list); } return [...map.entries()]; }, [events]);
  async function create(e: FormEvent) { e.preventDefault(); setError(""); setMessage(""); setSaving(true); try { const response = await fetch("/api/calendar", { method: "POST", headers: { "Content-Type": "application/json" }, body: JSON.stringify({ title, description, eventType, audience, startDate: new Date(startDate).toISOString(), endDate: new Date(endDate).toISOString(), allDay, location, status }) }); const data = await response.json(); if (!response.ok) throw new Error(data.error || "Unable to create event."); setTitle(""); setDescription(""); setLocation(""); setMessage("Calendar event created."); await load(); } catch (e) { setError(e instanceof Error ? e.message : "Unable to create event."); } finally { setSaving(false); } }
  async function remove(id: string) { if (!window.confirm("Delete this calendar event?")) return; const response = await fetch(`/api/calendar?id=${encodeURIComponent(id)}`, { method: "DELETE" }); const data = await response.json(); if (!response.ok) return setError(data.error || "Unable to delete event."); setMessage("Calendar event deleted."); await load(); }

  return <main className="admissions-shell"><header className="admissions-header"><div><div className="eyebrow">Aghaaz / School Calendar</div><h1>School Calendar</h1><p>One operational calendar for holidays, exams, meetings, deadlines and school activities.</p></div><div style={{display:"flex",gap:8,flexWrap:"wrap"}}><Link className="button" href="/">Home</Link><Link className="button" href="/academic-structure">Academic Structure</Link></div></header>
    {error && <div className="error" role="alert">{error}</div>}{message && <div className="success" role="status">{message}</div>}
    <section className="bottom-grid"><form className="panel" onSubmit={create}><div className="panel-heading"><div><h2>Create event</h2><p>Publish a school-wide or audience-specific event.</p></div></div><label>Title<input className="input" value={title} onChange={e=>setTitle(e.target.value)} required maxLength={160}/></label><label>Type<select className="input" value={eventType} onChange={e=>setEventType(e.target.value)}>{TYPES.map(x=><option key={x}>{x}</option>)}</select></label><label>Audience<select className="input" value={audience} onChange={e=>setAudience(e.target.value)}>{AUDIENCES.map(x=><option key={x}>{x}</option>)}</select></label><label>Starts<input className="input" type="datetime-local" value={startDate} onChange={e=>setStartDate(e.target.value)} required/></label><label>Ends<input className="input" type="datetime-local" value={endDate} onChange={e=>setEndDate(e.target.value)} required/></label><label>Location<input className="input" value={location} onChange={e=>setLocation(e.target.value)} maxLength={200}/></label><label>Description<textarea className="input" value={description} onChange={e=>setDescription(e.target.value)} maxLength={2000}/></label><label style={{display:"flex",alignItems:"center",gap:8}}><input type="checkbox" checked={allDay} onChange={e=>setAllDay(e.target.checked)}/> All-day event</label><label>Status<select className="input" value={status} onChange={e=>setStatus(e.target.value)}><option>PUBLISHED</option><option>DRAFT</option><option>CANCELLED</option></select></label><button className="primary-button" disabled={saving}>{saving ? "Saving…" : "Create event"}</button></form>
    <section className="panel"><div className="panel-heading"><div><h2>Upcoming</h2><p>Published events and administrator drafts for the next 120 days.</p></div></div>{loading ? <div className="empty-state">Loading calendar…</div> : grouped.length ? grouped.map(([day,list])=><div key={day} style={{marginBottom:20}}><h3>{day}</h3>{list.map(event=><article key={event.id} className="activity-row" style={{display:"block",marginTop:8}}><div style={{display:"flex",justifyContent:"space-between",gap:12}}><div><strong>{event.title}</strong><small>{event.allDay ? "All day" : `${new Date(event.startDate).toLocaleTimeString([], {hour:"numeric",minute:"2-digit"})} – ${new Date(event.endDate).toLocaleTimeString([], {hour:"numeric",minute:"2-digit"})}`} · {event.eventType} · {event.audience}{event.location ? ` · ${event.location}` : ""}</small>{event.description && <small>{event.description}</small>}</div><button className="button" onClick={()=>remove(event.id)}>Delete</button></div></article>)}</div>) : <div className="empty-state">No upcoming events.</div>}</section></section>
  </main>;
}
