"use client";
import { FormEvent, useEffect, useState } from "react";
type RequestRow={id:string;startDate:string;endDate:string;reason:string;status:string;reviewNote:string|null;reviewedAt:string|null;createdAt:string};
const fmt=(v:string)=>new Date(v).toLocaleDateString();
export default function ParentLeaveRequests(){const [rows,setRows]=useState<RequestRow[]>([]);const [start,setStart]=useState("");const [end,setEnd]=useState("");const [reason,setReason]=useState("");const [error,setError]=useState("");const [message,setMessage]=useState("");
async function load(){const r=await fetch("/api/parent/leave-requests",{cache:"no-store"});const b=await r.json();if(!r.ok)throw new Error(b.error);setRows(b.requests||[])}
useEffect(()=>{void load().catch(e=>setError(e.message||"Unable to load requests."))},[]);
async function submit(e:FormEvent){e.preventDefault();setError("");setMessage("");const r=await fetch("/api/parent/leave-requests",{method:"POST",headers:{"Content-Type":"application/json"},body:JSON.stringify({startDate:start,endDate:end,reason})});const b=await r.json();if(!r.ok){setError(b.error||"Unable to submit request.");return}setMessage("Leave request submitted.");setStart("");setEnd("");setReason("");await load()}
return <main className="container" style={{maxWidth:1000}}><header className="admissions-header"><div><div className="eyebrow">Aghaaz / Parent Portal</div><h1>Leave Requests</h1><p>Request and track planned student absences.</p></div><a className="button secondary" href="/parent">Back to dashboard</a></header>{error&&<div className="error">{error}</div>}{message&&<div className="success">{message}</div>}<section className="panel" style={{marginBottom:20}}><h2>New request</h2><form onSubmit={submit} className="form-grid"><label>Start date<input type="date" value={start} onChange={e=>setStart(e.target.value)} required/></label><label>End date<input type="date" value={end} onChange={e=>setEnd(e.target.value)} required/></label><label style={{gridColumn:"1/-1"}}>Reason<textarea value={reason} onChange={e=>setReason(e.target.value)} minLength={5} maxLength={500} required rows={4}/></label><button className="button" type="submit">Submit request</button></form></section><section className="panel"><h2>Request history</h2>{rows.length?<div className="table-wrap"><table><thead><tr><th>Dates</th><th>Reason</th><th>Status</th><th>Review</th></tr></thead><tbody>{rows.map(r=><tr key={r.id}><td>{fmt(r.startDate)} – {fmt(r.endDate)}</td><td>{r.reason}</td><td>{r.status}</td><td>{r.reviewNote||"—"}</td></tr>)}</tbody></table></div>:<div className="empty-state">No leave requests yet.</div>}</section></main>}
