"use client";

import { useEffect, useRef, useState } from "react";
import { useRouter } from "next/navigation";
import { deleteOfflineCache, discardOfflineOperation, getFailedOfflineOperations, getLastSyncResults, getOfflineCache, queueOfflineOperation, setOfflineCache } from "@/lib/offline-sync";

type FailedOperation = Awaited<ReturnType<typeof getFailedOfflineOperations>>[number];
type FormState = { studentName:string; dateOfBirth:string; age:string; gender:string; disability:string; medicalDetails:string; address:string; guardianCnic:string; motherCnic:string; phone1:string; phone2:string; emergency:string; guardianName:string; guardianEducation:string; guardianIncome:string; guardianOccupation:string; houseOwnership:string; rooms:string; motherName:string; motherEducation:string; motherOccupation:string; motherIncome:string; earners:string; vehicles:string; fridgeAc:string; mobileCount:string; nationality:string; totalChildren:string; boys:string; girls:string; schoolGoingChildren:string; villageTrips:string; livesWith:string; distance:string; previousSchool:string; previousGrade:string; previousResult:string; previousYear:string; leavingReason:string; desiredClass:string; guardianEmail:string; sessionName:string; remarks:string; photoDataUrl:string; };
const initial:FormState={studentName:"",dateOfBirth:"",age:"",gender:"",disability:"",medicalDetails:"",address:"",guardianCnic:"",motherCnic:"",phone1:"",phone2:"",emergency:"",guardianName:"",guardianEducation:"",guardianIncome:"",guardianOccupation:"",houseOwnership:"",rooms:"",motherName:"",motherEducation:"",motherOccupation:"",motherIncome:"",earners:"",vehicles:"",fridgeAc:"",mobileCount:"",nationality:"",totalChildren:"",boys:"",girls:"",schoolGoingChildren:"",villageTrips:"",livesWith:"",distance:"",previousSchool:"",previousGrade:"",previousResult:"",previousYear:"",leavingReason:"",desiredClass:"",guardianEmail:"",sessionName:"2026–27",remarks:"",photoDataUrl:""};

export default function NewAdmissionPage(){
 const router=useRouter(),videoRef=useRef<HTMLVideoElement|null>(null),canvasRef=useRef<HTMLCanvasElement|null>(null),streamRef=useRef<MediaStream|null>(null);
 const [form,setForm]=useState(initial),[camera,setCamera]=useState<"off"|"on"|"denied">("off"),[saving,setSaving]=useState(false),[error,setError]=useState(""),[hydrated,setHydrated]=useState(false),[pendingOperationKey,setPendingOperationKey]=useState(""),[failedOperations,setFailedOperations]=useState<FailedOperation[]>([]);
 const update=(key:keyof FormState,value:string)=>setForm(x=>({...x,[key]:value}));
 const calculateAge=(dateOfBirth:string)=>{
  if(!dateOfBirth)return "";
  const dob=new Date(`${dateOfBirth}T00:00:00`);
  if(Number.isNaN(dob.getTime()))return "";
  const today=new Date();
  let age=today.getFullYear()-dob.getFullYear();
  const month=today.getMonth()-dob.getMonth();
  if(month<0||(month===0&&today.getDate()<dob.getDate()))age--;
  return age>=0?String(age):"";
 };
 const updateDateOfBirth=(value:string)=>setForm(x=>({...x,dateOfBirth:value,age:calculateAge(value)}));
 async function startCamera(){setError("");try{const stream=await navigator.mediaDevices.getUserMedia({video:{facingMode:"user",width:{ideal:720},height:{ideal:900}},audio:false});streamRef.current=stream;if(videoRef.current){videoRef.current.srcObject=stream;await videoRef.current.play();}setCamera("on");}catch{setCamera("denied");setError("Camera access was not granted. You can still upload a passport-style photo.");}}
 function stopCamera(){streamRef.current?.getTracks().forEach(t=>t.stop());streamRef.current=null;setCamera("off");}
 function capture(){const video=videoRef.current,canvas=canvasRef.current;if(!video||!canvas)return;canvas.width=540;canvas.height=675;const ctx=canvas.getContext("2d");if(!ctx)return;const sourceRatio=video.videoWidth/video.videoHeight,targetRatio=4/5;let sx=0,sy=0,sw=video.videoWidth,sh=video.videoHeight;if(sourceRatio>targetRatio){sw=Math.round(sh*targetRatio);sx=Math.round((video.videoWidth-sw)/2);}else{sh=Math.round(sw/targetRatio);sy=Math.round((video.videoHeight-sh)/2);}ctx.drawImage(video,sx,sy,sw,sh,0,0,canvas.width,canvas.height);update("photoDataUrl",canvas.toDataURL("image/jpeg",0.82));stopCamera();}
 function handleFile(file:File|null){if(!file)return;if(!file.type.startsWith("image/")){setError("Please select an image file.");return;}const reader=new FileReader();reader.onload=()=>update("photoDataUrl",String(reader.result||""));reader.readAsDataURL(file);}
 useEffect(()=>{let cancelled=false;void getOfflineCache<FormState>("admission-draft").then(cached=>{if(cancelled)return;if(cached?.value){setForm(cached.value);setError(`Recovered local admission draft saved ${new Date(cached.savedAt).toLocaleString()}.`);}setHydrated(true);}).catch(()=>setHydrated(true));return()=>{cancelled=true;};},[]);
 useEffect(()=>{if(!hydrated)return;const timer=window.setTimeout(()=>{void setOfflineCache("admission-draft",form).catch(()=>{});},300);return()=>window.clearTimeout(timer);},[form,hydrated]);
 const refreshFailedOperations=()=>{void getFailedOfflineOperations().then(setFailedOperations).catch(()=>{});};
 const loadFailedOperation=(operation:FailedOperation)=>{
  const payload=(operation.payload&&typeof operation.payload==="object"&&!Array.isArray(operation.payload)?operation.payload:{}) as Record<string,unknown>;
  const formData=(payload.formData&&typeof payload.formData==="object"&&!Array.isArray(payload.formData)?payload.formData:{}) as Partial<FormState>;
  const next={...initial,...formData};
  next.studentName=String(payload.studentName??next.studentName??"");
  next.dateOfBirth=String(payload.dateOfBirth??next.dateOfBirth??"");
  next.gender=String(payload.gender??next.gender??"");
  next.guardianName=String(payload.guardianName??next.guardianName??"");
  next.phone1=String(payload.guardianPhone??next.phone1??"");
  next.guardianEmail=String(payload.guardianEmail??next.guardianEmail??"");
  next.desiredClass=String(payload.desiredClass??next.desiredClass??"");
  next.previousSchool=String(payload.previousSchool??next.previousSchool??"");
  next.sessionName=String(payload.sessionName??next.sessionName??"");
  next.remarks=String(payload.remarks??next.remarks??"");
  next.photoDataUrl=String(payload.photoDataUrl??next.photoDataUrl??"");
  setForm(next);
  setError(`Loaded failed admission for ${next.studentName||"this applicant"}. Correct the highlighted data, then submit again. The original failed operation is retained until you explicitly discard it.`);
 };
 useEffect(()=>{refreshFailedOperations();window.addEventListener("aghaaz:sync-complete",refreshFailedOperations);return()=>window.removeEventListener("aghaaz:sync-complete",refreshFailedOperations);},[]);
 useEffect(()=>{const onSync=async()=>{if(!pendingOperationKey)return;const results=await getLastSyncResults<{operationKey:string;operationType:string;applicationId?:string;applicationNumber?:string;enquiryNumber?:string;error?:string}>();const match=results.find((item)=>item.operationKey===pendingOperationKey);if(match){setPendingOperationKey("");if(match.operationType==="FAILED"){setError(`Admission synchronization failed: ${match.error||"Unable to submit this admission."}`);}else{setError(`Admission synchronized successfully. Application: ${match.applicationNumber||"assigned"} · Enquiry: ${match.enquiryNumber||"assigned"}.`);}}};window.addEventListener("aghaaz:sync-complete",onSync);void onSync();return()=>window.removeEventListener("aghaaz:sync-complete",onSync);},[pendingOperationKey]);
 useEffect(()=>()=>stopCamera(),[]);
 async function submit(e:React.FormEvent){e.preventDefault();const phone=form.phone1.trim();if(phone.length<7){setError("Phone number 1 must contain at least 7 characters.");return;}if(phone.length>30){setError("Phone number 1 must contain no more than 30 characters.");return;}setSaving(true);setError("");try{const formData=Object.fromEntries(Object.entries(form).filter(([k])=>k!=="photoDataUrl"));const payload={studentName:form.studentName,dateOfBirth:form.dateOfBirth||undefined,gender:form.gender||undefined,guardianName:form.guardianName,guardianPhone:form.phone1,guardianEmail:form.guardianEmail,desiredClass:form.desiredClass,previousSchool:form.previousSchool,sessionName:form.sessionName,remarks:form.remarks,photoDataUrl:form.photoDataUrl||undefined,formData};try{const response=await fetch("/api/admissions",{method:"POST",headers:{"Content-Type":"application/json"},body:JSON.stringify(payload)});const data=await response.json();if(!response.ok){const fieldErrors=data?.details?.fieldErrors??{};const issues=Object.entries(fieldErrors).flatMap(([field,messages])=>Array.isArray(messages)?messages.map((message)=>`${field}: ${String(message)}`):[]);throw new Error(issues.length?`Invalid application — ${issues.join("; ")}`:(data?.error||"Unable to create application."));}await deleteOfflineCache("admission-draft");router.push("/admissions");return;}catch(networkError){if(navigator.onLine && !(networkError instanceof TypeError))throw networkError;const operationKey=await queueOfflineOperation({entityType:"Application",entityId:crypto.randomUUID(),operationType:"CREATE_ADMISSION",payload});setPendingOperationKey(operationKey);await setOfflineCache("admission-last-submitted",form);await deleteOfflineCache("admission-draft");setError("Admission saved on this device. It will be submitted automatically when the internet connection returns.");} }catch(e){setError(e instanceof Error?e.message:"Unable to create application.");}finally{setSaving(false);}}
 const text=(label:keyof FormState,title:string,required=false)=><label>{title}{required?" *":""}<input className="input" required={required} value={form[label]} onChange={e=>update(label,e.target.value)}/></label>;
 const select=(label:keyof FormState,title:string,options:string[])=><label>{title}<select className="input" value={form[label]} onChange={e=>update(label,e.target.value)}><option value="">Select</option>{options.map(x=><option key={x}>{x}</option>)}</select></label>;
 return <main className="container admission-form-page"><header className="admissions-header"><div><div className="eyebrow">Aghaaz School / Admission Form</div><h1>New Admission Application</h1><p>Digital admission form based on the school’s Urdu paper form, with live student photo capture.</p></div><button className="button secondary" type="button" onClick={()=>router.back()}>Cancel</button></header>
 {error&&<div className="error">{error}</div>}
 {failedOperations.length>0&&<div className="error"><strong>Failed offline admissions ({failedOperations.length})</strong><div>These records were not discarded automatically. Review, correct and resubmit them, or explicitly discard a record after confirming it is no longer needed.</div>{failedOperations.map(operation=>{const payload=(operation.payload&&typeof operation.payload==="object"&&!Array.isArray(operation.payload)?operation.payload:{}) as Record<string,unknown>;return <div key={operation.operationKey} className="form-grid"><div><strong>{String(payload.studentName||"Unnamed admission")}</strong><div>{operation.failureMessage||"Synchronization failed."}</div></div><div><button type="button" className="button secondary" onClick={()=>loadFailedOperation(operation)}>Load into form</button><button type="button" className="button secondary" onClick={async()=>{if(window.confirm("Discard this failed offline admission? This does not delete any server record.")){await discardOfflineOperation(operation.operationKey);refreshFailedOperations();}}}>Discard</button></div></div>})}</div>}
 <form onSubmit={submit} className="admission-paper">
  <div className="admission-paper-head"><div className="admission-title"><div className="admission-logo">A</div><div><strong>آغاز اسکول داخلہ فارم</strong><small>Aghaaz School · School Admission Form</small></div></div><div className="admission-meta"><span>R.G / Application No.</span><b>Auto-generated on submission</b><span>Form date</span><b>{new Date().toLocaleDateString()}</b></div></div>
  <section className="admission-section admission-top-grid"><div><h2>طالب علم کی معلومات / Student Information</h2><div className="form-grid">
   {text("studentName","Student name",true)}<label>Date of birth<input className="input" type="date" value={form.dateOfBirth} onChange={e=>updateDateOfBirth(e.target.value)}/></label><label>Age<input className="input" type="number" value={form.age} readOnly aria-readonly="true" placeholder="Auto-calculated"/></label>{select("gender","Gender",["MALE","FEMALE","OTHER"])}{text("disability","Any physical / mental disability")}<label className="full">Physical / mental illness details<textarea className="input textarea small-textarea" value={form.medicalDetails} onChange={e=>update("medicalDetails",e.target.value)}/></label><label className="full">Full address<textarea className="input textarea small-textarea" value={form.address} onChange={e=>update("address",e.target.value)}/></label>
  </div></div>
  <div className="photo-card"><div className="photo-frame">{form.photoDataUrl?<img src={form.photoDataUrl} alt="Student preview"/>:<><span className="photo-placeholder">PHOTO</span><small>Passport-size</small></>}</div><canvas ref={canvasRef} hidden/><video ref={videoRef} className={camera==="on"?"camera-video":"camera-video hidden"} muted playsInline/><div className="photo-actions">{camera!=="on"&&<button type="button" className="button" onClick={startCamera}>Enable camera</button>}{camera==="on"&&<><button type="button" className="button" onClick={capture}>Capture photo</button><button type="button" className="button secondary" onClick={stopCamera}>Cancel</button></>}<label className="button secondary upload-photo">Upload photo<input type="file" accept="image/*" capture="user" onChange={e=>handleFile(e.target.files?.[0]||null)}/></label>{form.photoDataUrl&&<button type="button" className="photo-remove" onClick={()=>update("photoDataUrl","")}>Remove photo</button>}</div><p className="photo-note">Camera access is used only to capture the applicant photo for this admission record.</p></div></section>
  <section className="admission-section"><h2>رابطہ اور سرپرست / Guardian & Contact</h2><div className="form-grid">{text("guardianCnic","Father / guardian CNIC")}{text("motherCnic","Mother CNIC")}<label>Phone number 1 *<input className="input" required minLength={7} maxLength={30} value={form.phone1} onChange={e=>update("phone1",e.target.value)}/></label>{text("phone2","Phone number 2")}{text("emergency","Emergency number",true)}{text("guardianName","Father / guardian name",true)}{text("guardianEducation","Father / guardian education")}{text("guardianIncome","Father / guardian income")}{text("guardianOccupation","Father / guardian occupation")}{select("houseOwnership","House ownership",["Own","Rent","Other"])}{text("rooms","Number of rooms")}{text("motherName","Mother name")}{text("motherEducation","Mother education")}{text("motherOccupation","Mother occupation")}{text("motherIncome","Mother income")}{text("guardianEmail","Guardian email")}</div></section>
  <section className="admission-section"><h2>گھر اور خاندان / Household Information</h2><div className="form-grid">{text("earners","Number of earning members")}{text("vehicles","Vehicles")}{text("fridgeAc","Fridge / AC")}{text("mobileCount","Number of mobile phones")}{text("nationality","Nationality")}{text("totalChildren","Total number of children")}{text("boys","Boys")}{text("girls","Girls")}{text("schoolGoingChildren","Children attending school")}{text("villageTrips","Visits to village per year")}{text("livesWith","Child lives with")}{text("distance","Distance from school")}</div></section>
  <section className="admission-section"><h2>طالب علم کی پچھلی تعلیم / Previous Education</h2><div className="form-grid"><label className="full">Previous school name<input className="input" value={form.previousSchool} onChange={e=>update("previousSchool",e.target.value)}/></label>{text("previousGrade","Previous grade")}{text("previousResult","Previous grade result")}{text("previousYear","Year")}{text("leavingReason","Reason for leaving school")}{text("desiredClass","Proposed / desired class",true)}{text("sessionName","Academic session",true)}<label className="full">Additional remarks<textarea className="input textarea" value={form.remarks} onChange={e=>update("remarks",e.target.value)}/></label></div></section>
  <div className="admission-form-actions"><button type="button" className="button secondary" onClick={()=>router.back()}>Cancel</button><button className="button" disabled={saving}>{saving?"Saving application…":"Submit admission application"}</button></div>
 </form></main>;
}