"use client";
import { useEffect, useState } from "react";

type Entry={id:string;dayOfWeek:string;className:string;section?:string|null;subject:string;teacher:string;room?:string|null;startTime:string;endTime:string;period:number};
const days=["MONDAY","TUESDAY","WEDNESDAY","THURSDAY","FRIDAY","SATURDAY","SUNDAY"];
const labels:Record<string,string>={MONDAY:"Monday",TUESDAY:"Tuesday",WEDNESDAY:"Wednesday",THURSDAY:"Thursday",FRIDAY:"Friday",SATURDAY:"Saturday",SUNDAY:"Sunday"};
const initial={dayOfWeek:"MONDAY",className:"",section:"",subject:"",teacher:"",room:"",startTime:"08:00",endTime:"08:45",period:"1"};

export default function TimetablePage(){
 const [items,setItems]=useState<Entry[]>([]); const [loading,setLoading]=useState(true); const [saving,setSaving]=useState(false); const [error,setError]=useState(""); const [filter,setFilter]=useState(""); const [form,setForm]=useState(initial);
 const load=()=>{setLoading(true);const q=filter?`?class=${encodeURIComponent(filter)}`:"";fetch(`/api/timetable${q}`).then(async r=>{const d=await r.json();if(!r.ok)throw new Error(d.error||"Unable to load timetable");return d}).then(setItems).catch(e=>setError(e.message)).finally(()=>setLoading(false));};
 useEffect(()=>{load()},[filter]);
 async function create(e:React.FormEvent){e.preventDefault();setSaving(true);setError("");try{const r=await fetch("/api/timetable",{method:"POST",headers:{"Content-Type":"application/json"},body:JSON.stringify(form)});const d=await r.json();if(!r.ok)throw new Error(d.error||"Unable to create entry");setForm(initial);load()}catch(e){setError(e instanceof Error?e.message:"Unable to save entry")}finally{setSaving(false)}}
 async function remove(id:string){if(!confirm("Delete this timetable entry?"))return;const r=await fetch(`/api/timetable?id=${id}`,{method:"DELETE"});if(!r.ok){const d=await r.json();setError(d.error||"Unable to delete entry");return}setItems(x=>x.filter(i=>i.id!==id))}
 const grouped=days.map(day=>({day,items:items.filter(i=>i.dayOfWeek===day)})).filter(x=>x.items.length);
 return <main className="admissions-shell"><header className="admissions-header"><div><div className="eyebrow">Aghaaz School Management / Timetable</div><h1>Timetable</h1><p>Build and maintain the weekly class schedule.</p></div></header>{error&&<div className="error">{error}</div>}
 <section className="form-card"><h2>Add timetable period</h2><form className="form-grid" onSubmit={create}><label>Day<select className="input" value={form.dayOfWeek} onChange={e=>setForm({...form,dayOfWeek:e.target.value})}>{days.map(d=><option key={d}>{d}</option>)}</select></label><label>Class<input className="input" required value={form.className} onChange={e=>setForm({...form,className:e.target.value})} placeholder="Grade 5"/></label><label>Section<input className="input" value={form.section} onChange={e=>setForm({...form,section:e.target.value})} placeholder="A"/></label><label>Subject<input className="input" required value={form.subject} onChange={e=>setForm({...form,subject:e.target.value})} placeholder="Mathematics"/></label><label>Teacher<input className="input" required value={form.teacher} onChange={e=>setForm({...form,teacher:e.target.value})} placeholder="Teacher name"/></label><label>Room<input className="input" value={form.room} onChange={e=>setForm({...form,room:e.target.value})} placeholder="Room 4"/></label><label>Start time<input className="input" required type="time" value={form.startTime} onChange={e=>setForm({...form,startTime:e.target.value})}/></label><label>End time<input className="input" required type="time" value={form.endTime} onChange={e=>setForm({...form,endTime:e.target.value})}/></label><label>Period<input className="input" required type="number" min="1" max="20" value={form.period} onChange={e=>setForm({...form,period:e.target.value})}/></label><div><button className="button" disabled={saving}>{saving?"Saving…":"Add Period"}</button></div></form></section>
 <section className="applications-card"><div className="table-toolbar"><div><h2>Weekly schedule</h2><p>{items.length} period{items.length===1?"":"s"}</p></div><input className="input toolbar-search" value={filter} onChange={e=>setFilter(e.target.value)} placeholder="Filter by class…"/></div>{loading?<div className="empty-state">Loading timetable…</div>:items.length===0?<div className="empty-state"><strong>No timetable entries</strong><span>Add the first period above.</span></div>:<div className="table-wrap"><table><thead><tr><th>Day</th><th>Period</th><th>Time</th><th>Class</th><th>Subject</th><th>Teacher</th><th>Room</th><th></th></tr></thead><tbody>{grouped.flatMap(g=>g.items).map(x=><tr key={x.id}><td>{labels[x.dayOfWeek]}</td><td>{x.period}</td><td>{x.startTime} – {x.endTime}</td><td>{x.className}{x.section?` / ${x.section}`:""}</td><td><strong>{x.subject}</strong></td><td>{x.teacher}</td><td>{x.room||"—"}</td><td><button className="row-action" onClick={()=>remove(x.id)}>Delete</button></td></tr>)}</tbody></table></div>}</section></main>;
}
