"use client";
import Link from "next/link";
import { FormEvent, useEffect, useMemo, useState } from "react";

type Option={id:string;name:string;code?:string;sessionId?:string;gradeId?:string;employeeNumber?:string};
type Entry={id:string;dayOfWeek:string;className:string;section:string|null;subject:string;teacher:string;room:string|null;startTime:string;endTime:string;period:number;sessionName:string|null;gradeName:string|null;sectionName:string|null;subjectName:string|null;teacherName:string|null;academicSessionId:string|null;academicGradeId:string|null;academicSectionId:string|null;academicSubjectId:string|null;teacherStaffId:string|null};
type Structure={sessions:Option[];grades:Option[];sections:Option[];subjects:Option[];staff:Option[]};
const days=["MONDAY","TUESDAY","WEDNESDAY","THURSDAY","FRIDAY","SATURDAY"];
const labels:Record<string,string>={MONDAY:"Monday",TUESDAY:"Tuesday",WEDNESDAY:"Wednesday",THURSDAY:"Thursday",FRIDAY:"Friday",SATURDAY:"Saturday"};
const initial={dayOfWeek:"MONDAY",academicSessionId:"",academicGradeId:"",academicSectionId:"",academicSubjectId:"",teacherStaffId:"",room:"",startTime:"08:00",endTime:"08:45",period:"1"};

export default function TimetablePage(){
 const [structure,setStructure]=useState<Structure>({sessions:[],grades:[],sections:[],subjects:[],staff:[]});
 const [items,setItems]=useState<Entry[]>([]); const [loading,setLoading]=useState(true); const [saving,setSaving]=useState(false); const [error,setError]=useState(""); const [sessionFilter,setSessionFilter]=useState(""); const [teacherFilter,setTeacherFilter]=useState(""); const [form,setForm]=useState(initial);
 useEffect(()=>{fetch("/api/academic-structure").then(async r=>{const d=await r.json();if(!r.ok)throw new Error(d.error||"Unable to load academic structure.");setStructure({sessions:d.sessions||[],grades:d.grades||[],sections:d.sections||[],subjects:d.subjects||[],staff:(d.staff||[]).filter((x:Option)=>!x.employeeNumber||true)});}).catch(e=>setError(e instanceof Error?e.message:"Unable to load academic structure."));},[]);
 const grades=useMemo(()=>structure.grades.filter(x=>!form.academicSessionId||x.sessionId===form.academicSessionId),[structure.grades,form.academicSessionId]);
 const sections=useMemo(()=>structure.sections.filter(x=>!form.academicGradeId||x.gradeId===form.academicGradeId),[structure.sections,form.academicGradeId]);
 useEffect(()=>{if(form.academicGradeId&&!grades.some(x=>x.id===form.academicGradeId))setForm(x=>({...x,academicGradeId:"",academicSectionId:""}));},[grades,form.academicGradeId]);
 useEffect(()=>{if(form.academicSectionId&&!sections.some(x=>x.id===form.academicSectionId))setForm(x=>({...x,academicSectionId:""}));},[sections,form.academicSectionId]);
 const load=()=>{setLoading(true);const p=new URLSearchParams();if(sessionFilter)p.set("sessionId",sessionFilter);if(teacherFilter)p.set("teacherStaffId",teacherFilter);fetch(`/api/timetable${p.toString()?`?${p}`:""}`).then(async r=>{const d=await r.json();if(!r.ok)throw new Error(d.error||"Unable to load timetable");return d}).then(setItems).catch(e=>setError(e instanceof Error?e.message:"Unable to load timetable")).finally(()=>setLoading(false));};
 useEffect(()=>{load()},[sessionFilter,teacherFilter]);
 async function create(e:FormEvent){e.preventDefault();setSaving(true);setError("");try{const r=await fetch("/api/timetable",{method:"POST",headers:{"Content-Type":"application/json"},body:JSON.stringify(form)});const d=await r.json();if(!r.ok)throw new Error(d.error||"Unable to create entry");setForm(initial);load();}catch(e){setError(e instanceof Error?e.message:"Unable to save entry")}finally{setSaving(false)}}
 async function remove(id:string){if(!confirm("Delete this timetable entry?"))return;const r=await fetch(`/api/timetable?id=${id}`,{method:"DELETE"});if(!r.ok){const d=await r.json();setError(d.error||"Unable to delete entry");return}setItems(x=>x.filter(i=>i.id!==id));}
 const grouped=days.map(day=>({day,items:items.filter(i=>i.dayOfWeek===day)})).filter(x=>x.items.length);
 return <main className="admissions-shell"><header className="admissions-header"><div><div className="eyebrow">Aghaaz / Timetable</div><h1>Weekly timetable</h1><p>Schedule real academic sections against assigned subjects and active teachers. Conflicts are blocked automatically.</p></div><Link className="primary-button" href="/academic-structure">Academic structure</Link></header>{error&&<div className="error">{error}</div>}
 <section className="form-card"><h2>Add teaching period</h2><form className="form-grid" onSubmit={create}><label>Academic year<select className="input" required value={form.academicSessionId} onChange={e=>setForm({...form,academicSessionId:e.target.value,academicGradeId:"",academicSectionId:""})}><option value="">Select…</option>{structure.sessions.map(x=><option key={x.id} value={x.id}>{x.name}</option>)}</select></label><label>Grade<select className="input" required value={form.academicGradeId} onChange={e=>setForm({...form,academicGradeId:e.target.value,academicSectionId:""})}><option value="">Select…</option>{grades.map(x=><option key={x.id} value={x.id}>{x.name}{x.code?` (${x.code})`:""}</option>)}</select></label><label>Section<select className="input" required value={form.academicSectionId} onChange={e=>setForm({...form,academicSectionId:e.target.value})}><option value="">Select…</option>{sections.map(x=><option key={x.id} value={x.id}>{x.name}</option>)}</select></label><label>Subject<select className="input" required value={form.academicSubjectId} onChange={e=>setForm({...form,academicSubjectId:e.target.value})}><option value="">Select…</option>{structure.subjects.map(x=><option key={x.id} value={x.id}>{x.name}{x.code?` (${x.code})`:""}</option>)}</select></label><label>Teacher<select className="input" required value={form.teacherStaffId} onChange={e=>setForm({...form,teacherStaffId:e.target.value})}><option value="">Select…</option>{structure.staff.map(x=><option key={x.id} value={x.id}>{x.name}{x.employeeNumber?` · ${x.employeeNumber}`:""}</option>)}</select></label><label>Day<select className="input" value={form.dayOfWeek} onChange={e=>setForm({...form,dayOfWeek:e.target.value})}>{days.map(d=><option key={d}>{d}</option>)}</select></label><label>Start time<input className="input" required type="time" value={form.startTime} onChange={e=>setForm({...form,startTime:e.target.value})}/></label><label>End time<input className="input" required type="time" value={form.endTime} onChange={e=>setForm({...form,endTime:e.target.value})}/></label><label>Period<input className="input" required type="number" min="1" max="20" value={form.period} onChange={e=>setForm({...form,period:e.target.value})}/></label><label>Room<input className="input" value={form.room} onChange={e=>setForm({...form,room:e.target.value})} placeholder="Room 4"/></label><div><button className="button" disabled={saving}>{saving?"Saving…":"Add period"}</button></div></form></section>
 <section className="applications-card"><div className="table-toolbar"><div><h2>Weekly schedule</h2><p>{items.length} period{items.length===1?"":"s"}</p></div><div style={{display:"flex",gap:8,flexWrap:"wrap"}}><select className="input" value={sessionFilter} onChange={e=>setSessionFilter(e.target.value)}><option value="">All academic years</option>{structure.sessions.map(x=><option key={x.id} value={x.id}>{x.name}</option>)}</select><select className="input" value={teacherFilter} onChange={e=>setTeacherFilter(e.target.value)}><option value="">All teachers</option>{structure.staff.map(x=><option key={x.id} value={x.id}>{x.name}</option>)}</select></div></div>{loading?<div className="empty-state">Loading timetable…</div>:items.length===0?<div className="empty-state"><strong>No timetable entries</strong><span>Add a period above or change the filters.</span></div>:<div className="table-wrap"><table><thead><tr><th>Day</th><th>Period</th><th>Time</th><th>Class</th><th>Subject</th><th>Teacher</th><th>Room</th><th></th></tr></thead><tbody>{grouped.flatMap(g=>g.items).map(x=><tr key={x.id}><td>{labels[x.dayOfWeek]||x.dayOfWeek}</td><td>{x.period}</td><td>{x.startTime} – {x.endTime}</td><td>{x.gradeName||x.className}{x.sectionName?` / ${x.sectionName}`:x.section?` / ${x.section}`:""}</td><td><strong>{x.subjectName||x.subject}</strong></td><td>{x.teacherName||x.teacher}</td><td>{x.room||"—"}</td><td><button className="row-action" onClick={()=>remove(x.id)}>Delete</button></td></tr>)}</tbody></table></div>}</section></main>;
}
