"use client";
import Link from "next/link";
import { useEffect, useState } from "react";

type Student = { id: string; studentName?: string; registry?: { grNumber: string }; enrollment?: { admissionNumber?: string; status?: string } };
type RecordRow = { id:string; enrollmentId:string; studentName:string; grNumber:string|null; occurredAt:string; category:string; severity:string; title:string; description:string|null; actionTaken:string|null; followUpDue:string|null; followUpNote:string|null; status:string; parentNotified:boolean; resolutionNote:string|null };
const blank={enrollmentId:"",category:"BEHAVIOUR",severity:"LOW",title:"",description:"",actionTaken:"",followUpDue:"",followUpNote:""};
export default function BehaviourPage(){
 const [students,setStudents]=useState<Student[]>([]),[records,setRecords]=useState<RecordRow[]>([]),[form,setForm]=useState(blank),[q,setQ]=useState(""),[status,setStatus]=useState("ALL"),[message,setMessage]=useState(""),[error,setError]=useState(""),[saving,setSaving]=useState(false);
 async function load(){const [s,r]=await Promise.all([fetch("/api/students",{cache:"no-store"}),fetch("/api/behaviour",{cache:"no-store"})]);const sd=await s.json(),rd=await r.json();if(!s.ok)throw Error(sd.error||"Unable to load students");if(!r.ok)throw Error(rd.error||"Unable to load behaviour");setStudents(sd);setRecords(rd.records||[])}
 useEffect(()=>{load().catch(e=>setError(e.message))},[]);
 const filtered=records.filter(r=>(status==="ALL"||r.status===status)&&[r.studentName,r.grNumber,r.category,r.severity,r.title].join(" ").toLowerCase().includes(q.toLowerCase()));
 async function submit(e:React.FormEvent){e.preventDefault();setSaving(true);setError("");setMessage("");try{const body={...form,followUpDue:form.followUpDue?new Date(`${form.followUpDue}T12:00:00`).toISOString():undefined};const r=await fetch("/api/behaviour",{method:"POST",headers:{"Content-Type":"application/json"},body:JSON.stringify(body)});const d=await r.json();if(!r.ok)throw Error(d.error||"Unable to record behaviour");setMessage(d.parentNotification?"Record saved and parent notification queued.":"Behaviour record saved.");setForm(blank);await load()}catch(e){setError(e instanceof Error?e.message:"Unable to save record.")}finally{setSaving(false)}}
 async function update(id:string,next:string){setError("");const r=await fetch("/api/behaviour",{method:"PATCH",headers:{"Content-Type":"application/json"},body:JSON.stringify({id,status:next})});const d=await r.json();if(!r.ok)setError(d.error||"Unable to update record");else await load()}
 return <main className="container"><header className="admissions-header"><div><div className="eyebrow">Aghaaz / Students / Wellbeing</div><h1>Behaviour & Wellbeing</h1><p>Record observations, incidents, follow-up and resolution without losing the student's wider context.</p></div><div className="toolbar-actions"><Link className="button secondary" href="/students">Students</Link><Link className="button secondary" href="/monitor">Monitor</Link></div></header>
 {error&&<div className="error" role="alert">{error}</div>}{message&&<div className="success" role="status">{message}</div>}
 <section className="bottom-grid"><div className="panel"><div className="panel-heading"><div><h2>Record an observation</h2><p>Use factual notes and document the action taken.</p></div></div><form onSubmit={submit} style={{display:"grid",gap:12}}><label>Student<select className="input" required value={form.enrollmentId} onChange={e=>setForm({...form,enrollmentId:e.target.value})}><option value="">Select student</option>{students.filter(s=>s.enrollment?.status!=="inactive").map(s=><option key={s.id} value={s.enrollment?.admissionNumber||s.id}>{s.studentName||"Student"} · {s.registry?.grNumber||"No GR"}</option>)}</select></label><small>Selecting by admission number requires the API to resolve enrollment; if unavailable, use Student 360.</small><label>Category<input className="input" required value={form.category} onChange={e=>setForm({...form,category:e.target.value})}/></label><label>Severity<select className="input" value={form.severity} onChange={e=>setForm({...form,severity:e.target.value})}><option>LOW</option><option>MEDIUM</option><option>HIGH</option><option>CRITICAL</option></select></label><label>Title<input className="input" required value={form.title} onChange={e=>setForm({...form,title:e.target.value})} placeholder="e.g. Repeated late arrival"/></label><label>Description<textarea className="input" rows={3} value={form.description} onChange={e=>setForm({...form,description:e.target.value})}/></label><label>Action taken<textarea className="input" rows={2} value={form.actionTaken} onChange={e=>setForm({...form,actionTaken:e.target.value})}/></label><label>Follow-up due<input className="input" type="date" value={form.followUpDue} onChange={e=>setForm({...form,followUpDue:e.target.value})}/></label><label>Follow-up note<textarea className="input" rows={2} value={form.followUpNote} onChange={e=>setForm({...form,followUpNote:e.target.value})}/></label><button className="primary-button" disabled={saving}>{saving?"Saving…":"Save Behaviour Record"}</button></form></div>
 <div className="panel"><div className="panel-heading"><div><h2>Workflow</h2><p>Open → In Progress → Resolved.</p></div></div><div className="activity-row"><div><strong>Factual record</strong><small>Keep incident/observation details separate from conclusions.</small></div></div><div className="activity-row"><div><strong>Follow-up</strong><small>Assign a due date and note for the next action.</small></div></div><div className="activity-row"><div><strong>Parent communication</strong><small>Saving a record queues a parent notification through Aghaaz communication preferences.</small></div></div><div className="activity-row"><div><strong>Resolution</strong><small>Resolve only after the follow-up has been completed and documented.</small></div></div></div></section>
 <section className="applications-card"><div className="table-toolbar"><div><h2>Behaviour records</h2><p>{filtered.length} records shown.</p></div><div className="toolbar-actions"><input className="search-input" placeholder="Search student, GR, category…" value={q} onChange={e=>setQ(e.target.value)}/><select className="filter-select" value={status} onChange={e=>setStatus(e.target.value)}><option>ALL</option><option>OPEN</option><option>IN_PROGRESS</option><option>RESOLVED</option><option>DISMISSED</option></select></div></div><div className="table-wrap"><table><thead><tr><th>Date</th><th>Student</th><th>Category</th><th>Severity</th><th>Issue</th><th>Status</th><th>Parent</th><th></th></tr></thead><tbody>{filtered.length?filtered.map(r=><tr key={r.id}><td>{new Date(r.occurredAt).toLocaleDateString()}</td><td><strong>{r.studentName}</strong><small>{r.grNumber||"—"}</small></td><td>{r.category}</td><td><span className="status-pill">{r.severity}</span></td><td>{r.title}<small>{r.followUpDue?`Follow-up ${new Date(r.followUpDue).toLocaleDateString()}`:""}</small></td><td>{r.status}</td><td>{r.parentNotified?"Queued":"—"}</td><td>{r.status!=="RESOLVED"&&<button className="row-action" onClick={()=>update(r.id,"RESOLVED")}>Resolve</button>}</td></tr>):<tr><td colSpan={8}>No behaviour records found.</td></tr>}</tbody></table></div></section>
 </main>}
