"use client";

import Link from "next/link";
import { FormEvent, useEffect, useMemo, useState } from "react";

type Staff = { id: string; employeeNumber: string; name: string; staffType: string; designation: string; phone: string | null; email: string | null; subject: string | null; qualifications: string | null; assignedClasses: string | null; salary: string | number | null; active: boolean; joiningDate: string; };
type FormState = { name: string; designation: string; phone: string; email: string; subject: string; qualifications: string; assignedClasses: string; salary: string; };
const empty: FormState = { name: "", designation: "Teacher", phone: "", email: "", subject: "", qualifications: "", assignedClasses: "", salary: "" };

export default function TeachersPage() {
  const [rows, setRows] = useState<Staff[]>([]); const [form, setForm] = useState<FormState>(empty); const [query, setQuery] = useState(""); const [error, setError] = useState(""); const [saving, setSaving] = useState(false);
  async function load() { const response = await fetch("/api/staff"); const data = await response.json(); if (!response.ok) throw new Error(data.error || "Unable to load teachers."); setRows((data.staff as Staff[]).filter(x => x.staffType === "TEACHER")); }
  useEffect(() => { load().catch(e => setError(e instanceof Error ? e.message : "Unable to load teachers.")); }, []);
  const filtered = useMemo(() => rows.filter(x => `${x.name} ${x.employeeNumber} ${x.subject || ""} ${x.assignedClasses || ""}`.toLowerCase().includes(query.toLowerCase())), [rows, query]);
  async function submit(event: FormEvent) { event.preventDefault(); setSaving(true); setError(""); try { const response = await fetch("/api/staff", { method: "POST", headers: { "Content-Type": "application/json" }, body: JSON.stringify({ ...form, staffType: "TEACHER", salary: form.salary || undefined }) }); const data = await response.json(); if (!response.ok) throw new Error(data.error || "Unable to add teacher."); setRows(prev => [...prev, data].sort((a, b) => a.name.localeCompare(b.name))); setForm(empty); } catch (e) { setError(e instanceof Error ? e.message : "Unable to add teacher."); } finally { setSaving(false); } }
  return <main className="container"><header className="admissions-header"><div><div className="eyebrow">Aghaaz / People / Teachers</div><h1>Teachers</h1><p>Maintain the teaching directory, qualifications and class responsibilities.</p></div><div style={{display:"flex",gap:8}}><Link className="secondary-button" href="/teachers/workload">Workload</Link><Link className="primary-button" href="/staff">Staff directory</Link></div></header>{error && <div className="login-error" role="alert">{error}</div>}<section className="bottom-grid"><div className="panel"><div className="panel-heading"><div><h2>Add teacher</h2><p>Employee number is generated automatically.</p></div></div><form onSubmit={submit} className="login-form"><label>Name<input required value={form.name} onChange={e => setForm({...form, name:e.target.value})}/></label><label>Designation<input required value={form.designation} onChange={e => setForm({...form, designation:e.target.value})}/></label><label>Phone<input value={form.phone} onChange={e => setForm({...form, phone:e.target.value})}/></label><label>Email<input type="email" value={form.email} onChange={e => setForm({...form, email:e.target.value})}/></label><label>Subject<input value={form.subject} onChange={e => setForm({...form, subject:e.target.value})} placeholder="e.g. Mathematics"/></label><label>Qualifications<input value={form.qualifications} onChange={e => setForm({...form, qualifications:e.target.value})}/></label><label>Assigned classes<input value={form.assignedClasses} onChange={e => setForm({...form, assignedClasses:e.target.value})} placeholder="Use Academic Structure for canonical assignments"/></label><label>Monthly salary<input type="number" min="0" step="0.01" value={form.salary} onChange={e => setForm({...form, salary:e.target.value})}/></label><button type="submit" disabled={saving}>{saving ? "Adding…" : "Add teacher"}</button></form></div><div className="panel"><div className="panel-heading"><div><h2>Teaching team</h2><p>{filtered.length} teacher{filtered.length === 1 ? "" : "s"}</p></div><input value={query} onChange={e => setQuery(e.target.value)} placeholder="Search teachers" style={{maxWidth:240}}/></div>{filtered.map(row => <div className="activity-row" key={row.id}><span className="avatar">{row.name.slice(0,2).toUpperCase()}</span><div style={{minWidth:0}}><Link href={`/staff/${row.id}`}><strong>{row.name}</strong></Link><small>{row.employeeNumber} · {row.designation}{row.subject ? ` · ${row.subject}` : ""}</small><small>{row.assignedClasses || "No classes assigned"}</small></div><span className="status-badge">{row.active ? "Active" : "Inactive"}</span><Link className="row-action" href={`/staff/${row.id}`}>Manage</Link></div>)}</div></section></main>;
}
