"use client";
import { useEffect,useState } from "react";
type Session={id:string;name:string}; type Grade={id:string;name:string;sessionId:string}; type Section={id:string;gradeId:string;name:string;gradeName:string};
type Promotion={id:string;createdAt:string;sourceSessionName:string;sourceGradeName:string;sourceSectionName:string;targetSessionName:string;targetGradeName:string;targetSectionName:string;studentCount:number;status:string;note:string|null};
export default function BatchPromotion(){const [sessions,setSessions]=useState<Session[]>([]),[grades,setGrades]=useState<Grade[]>([]),[sections,setSections]=useState<Section[]>([]),[sourceSession,setSourceSession]=useState(''),[targetSession,setTargetSession]=useState(''),[sourceGrade,setSourceGrade]=useState(''),[targetGrade,setTargetGrade]=useState(''),[sourceSection,setSourceSection]=useState(''),[targetSection,setTargetSection]=useState(''),[note,setNote]=useState(''),[history,setHistory]=useState<Promotion[]>([]),[error,setError]=useState(''),[saved,setSaved]=useState('');
 async function load(){const r=await fetch('/api/academic-structure');const d=await r.json();if(!r.ok)throw new Error(d.error||'Unable to load academic structure');setSessions(d.sessions||[]);setGrades(d.grades||[]);setSections(d.sections||[]);const h=await fetch('/api/batch-promotion');const hd=await h.json();if(h.ok)setHistory((hd.promotions||[]) as Promotion[])}useEffect(()=>{load().catch(e=>setError(e.message))},[]);
 const sg=grades.filter(g=>!sourceSession||g.sessionId===sourceSession),tg=grades.filter(g=>!targetSession||g.sessionId===targetSession);const ss=sections.filter(s=>s.gradeId===sourceGrade),ts=sections.filter(s=>s.gradeId===targetGrade);
 async function promote(){setError('');setSaved('');if(!sourceSection||!targetSection)return setError('Select both source and target sections.');if(!confirm('Promote all active students from the selected source section?'))return;const r=await fetch('/api/batch-promotion',{method:'POST',headers:{'Content-Type':'application/json'},body:JSON.stringify({sourceSectionId:sourceSection,targetSectionId:targetSection,note})});const d=await r.json();if(!r.ok)return setError(d.error||'Promotion failed.');setSaved(`${d.count} student(s) promoted successfully.`);setNote('');await load()}
 return <main className="container"><header className="admissions-header"><div><div className="eyebrow">Aghaaz / Enrollment Lifecycle</div><h1>Batch Promotion</h1><p>Move all active students from one academic section to another while preserving enrollment history.</p></div></header>{error&&<div className="alert error">{error}</div>}{saved&&<div className="alert success">{saved}</div>}
 <section className="module-grid"><div className="module-card"><h3>Source</h3><label className="field"><span>Academic year</span><select value={sourceSession} onChange={e=>{setSourceSession(e.target.value);setSourceGrade('');setSourceSection('')}}><option value="">Select year</option>{sessions.map(s=><option key={s.id} value={s.id}>{s.name}</option>)}</select></label><label className="field"><span>Grade</span><select value={sourceGrade} onChange={e=>{setSourceGrade(e.target.value);setSourceSection('')}}><option value="">Select grade</option>{sg.map(g=><option key={g.id} value={g.id}>{g.name}</option>)}</select></label><label className="field"><span>Section</span><select value={sourceSection} onChange={e=>setSourceSection(e.target.value)}><option value="">Select section</option>{ss.map(s=><option key={s.id} value={s.id}>{s.name}</option>)}</select></label></div><div className="module-card"><h3>Target</h3><label className="field"><span>Academic year</span><select value={targetSession} onChange={e=>{setTargetSession(e.target.value);setTargetGrade('');setTargetSection('')}}><option value="">Select year</option>{sessions.map(s=><option key={s.id} value={s.id}>{s.name}</option>)}</select></label><label className="field"><span>Grade</span><select value={targetGrade} onChange={e=>{setTargetGrade(e.target.value);setTargetSection('')}}><option value="">Select grade</option>{tg.map(g=><option key={g.id} value={g.id}>{g.name}</option>)}</select></label><label className="field"><span>Section</span><select value={targetSection} onChange={e=>setTargetSection(e.target.value)}><option value="">Select section</option>{ts.map(s=><option key={s.id} value={s.id}>{s.name}</option>)}</select></label></div></section>
 <section className="applications-card"><label className="field"><span>Promotion note (optional)</span><textarea value={note} onChange={e=>setNote(e.target.value)} placeholder="End-of-year promotion"/></label><button className="button" onClick={promote}>Promote active students</button></section>
 <section className="applications-card"><h2>Promotion history</h2><div className="table-wrap"><table><thead><tr><th>Date</th><th>From</th><th>To</th><th>Students</th><th>Status</th><th>Note</th></tr></thead><tbody>{history.length?history.map(p=><tr key={p.id}><td>{p.createdAt?new Date(p.createdAt).toLocaleString():'—'}</td><td>{p.sourceSessionName} · {p.sourceGradeName} · {p.sourceSectionName}</td><td>{p.targetSessionName} · {p.targetGradeName} · {p.targetSectionName}</td><td>{p.studentCount}</td><td>{p.status}</td><td>{p.note||''}</td></tr>):<tr><td colSpan={6}>No batch promotions recorded.</td></tr>}</tbody></table></div></section></main>}
