"use client";
import Link from "next/link";
import { FormEvent,useEffect,useState } from "react";
type Student={id:string;studentName:string;enrollment?:{id:string;className:string;section:string|null;status:string}|null;registry?:{grNumber:string}|null};
type Account={id:string;user:{name:string;username:string;active:boolean};students:{enrollment:{id:string;application:{studentName:string}}}[]};
export default function FamilyAccounts(){
 const [students,setStudents]=useState<Student[]>([]),[accounts,setAccounts]=useState<Account[]>([]),[selected,setSelected]=useState<string[]>([]),[name,setName]=useState(""),[username,setUsername]=useState(""),[password,setPassword]=useState(""),[error,setError]=useState(""),[saving,setSaving]=useState(false);
 async function load(){const [s,a]=await Promise.all([fetch("/api/students"),fetch("/api/admin/family-accounts")]);const sd=await s.json(),ad=await a.json();if(!s.ok)throw new Error(sd.error||"Unable to load students.");if(!a.ok)throw new Error(ad.error||"Unable to load Family accounts.");setStudents(sd);setAccounts(ad.accounts||[])}
 useEffect(()=>{load().catch(e=>setError(e.message))},[]);
 function toggle(id:string){setSelected(x=>x.includes(id)?x.filter(v=>v!==id):[...x,id])}
 async function create(e:FormEvent){e.preventDefault();setSaving(true);setError("");try{const r=await fetch("/api/admin/family-accounts",{method:"POST",headers:{"Content-Type":"application/json"},body:JSON.stringify({name,username,password,enrollmentIds:selected})});const b=await r.json();if(!r.ok)throw new Error(b.error||"Unable to create Family account.");setAccounts(x=>[b.account,...x]);setName("");setUsername("");setPassword("");setSelected([])}catch(e){setError(e instanceof Error?e.message:"Unable to create Family account.")}finally{setSaving(false)}}
 const linked=new Set(accounts.flatMap(a=>a.students.map(s=>s.enrollment.id)));
 return <main className="app-shell"><aside className="sidebar"><div className="brand"><span className="brand-mark">A</span><span>Aghaaz</span></div><div className="school-name">School Management</div><nav className="nav"><Link className="nav-item" href="/admin">⚙ Administration</Link><Link className="nav-item active" href="/admin/family-accounts">Family Accounts</Link><Link className="nav-item" href="/students">▣ Students</Link></nav></aside><section className="main-content"><header className="topbar"><div className="mobile-brand"><span className="brand-mark">A</span> Aghaaz</div></header><div className="page"><section className="hero"><div><div className="eyebrow">Administration / Family Accounts</div><h1>Family Portal Accounts</h1><p>Create school-issued username/password credentials and link one or more students. Family accounts are read-only for official records.</p></div></section>{error&&<div className="error" role="alert">{error}</div>}<section className="bottom-grid"><div className="panel"><div className="panel-heading"><div><h2>Create Family account</h2><p>Password change on first login is optional.</p></div></div><form onSubmit={create} className="form-grid" style={{marginTop:20}}><label>Family name<input className="input" value={name} onChange={e=>setName(e.target.value)} required minLength={2}/></label><label>Username<input className="input" value={username} onChange={e=>setUsername(e.target.value)} required placeholder="family-001"/></label><label>Initial password<input className="input" type="password" value={password} onChange={e=>setPassword(e.target.value)} required minLength={8}/></label><div className="full"><strong>Link students</strong>{students.filter(s=>s.enrollment&&!linked.has(s.enrollment.id)).map(s=><label key={s.enrollment!.id} style={{display:"flex",gap:8,alignItems:"center",marginTop:8}}><input type="checkbox" checked={selected.includes(s.enrollment!.id)} onChange={()=>toggle(s.enrollment!.id)}/><span>{s.studentName} · {s.registry?.grNumber||s.enrollment!.id} · {s.enrollment!.className}{s.enrollment!.section?" "+s.enrollment!.section:""}</span></label>)}</div><button className="button full" type="submit" disabled={saving||!selected.length}>{saving?"Creating…":"Create Family account"}</button></form></div><div className="panel"><div className="panel-heading"><div><h2>Existing Family accounts</h2><p>{accounts.length} account{accounts.length===1?"":"s"}</p></div></div>{accounts.length?accounts.map(a=><div className="activity-row" key={a.id}><span className="avatar">{a.user.name.slice(0,2).toUpperCase()}</span><div><strong>{a.user.name}</strong><small>Username: {a.user.username}</small><small>Students: {a.students.map(s=>s.enrollment.application.studentName).join(", ")}</small><small>{a.user.active?"Active":"Disabled"}</small></div></div>):<div className="empty-state">No Family accounts yet.</div>}</div></section></div></section></main>}