export const AGHAAZ_IB_2025_2026 = {
  className: "IB",
  subjects: [
    { term: "FIRST", subject: "English", maxMarks: 100, components: [{ name: "Oral", maxMarks: 6 }, { name: "Written", maxMarks: 94 }] },
    { term: "FIRST", subject: "Science", maxMarks: 100, components: [] },
    { term: "FIRST", subject: "Social Studies", maxMarks: 100, components: [] },
    { term: "FIRST", subject: "Mathematics", maxMarks: 100, components: [] },
    { term: "FIRST", subject: "Urdu", maxMarks: 100, components: [{ name: "Oral", maxMarks: 5 }, { name: "Written", maxMarks: 95 }] },
    { term: "FIRST", subject: "Islamiat", maxMarks: 100, components: [{ name: "Oral", maxMarks: 20 }, { name: "Written", maxMarks: 80 }] },
    { term: "SECOND", subject: "English", maxMarks: 75, components: [] },
    { term: "SECOND", subject: "Science", maxMarks: 75, components: [] },
    { term: "SECOND", subject: "Social Studies", maxMarks: 75, components: [] },
    { term: "SECOND", subject: "English Reading", maxMarks: 25, components: [] },
    { term: "SECOND", subject: "Urdu Reading", maxMarks: 25, components: [] },
    { term: "SECOND", subject: "Mathematics", maxMarks: 100, components: [] },
    { term: "SECOND", subject: "Urdu", maxMarks: 100, components: [] },
    { term: "SECOND", subject: "Islamiat", maxMarks: 100, components: [] },
    { term: "THIRD", subject: "English", maxMarks: 100, components: [{ name: "Oral", maxMarks: 10 }, { name: "Written", maxMarks: 90 }] },
    { term: "THIRD", subject: "Science", maxMarks: 100, components: [] },
    { term: "THIRD", subject: "Social Studies", maxMarks: 100, components: [] },
    { term: "THIRD", subject: "English Reading", maxMarks: 25, components: [] },
    { term: "THIRD", subject: "Urdu Reading", maxMarks: 25, components: [] },
    { term: "THIRD", subject: "Mathematics", maxMarks: 100, components: [] },
    { term: "THIRD", subject: "Urdu", maxMarks: 100, components: [{ name: "Oral", maxMarks: 10 }, { name: "Written", maxMarks: 90 }] },
    { term: "THIRD", subject: "Islamiat", maxMarks: 100, components: [{ name: "Oral", maxMarks: 25 }, { name: "Written", maxMarks: 75 }] },
  ],
} as const;
