"use client";
import { useEffect, useState } from "react";
type Card={id:string;sessionName:string;releasedAt:string;snapshot:unknown};
type Data={schoolName:string;reportCards:Card[]};
const fmt=(v:string)=>new Date(v).toLocaleDateString();
const label=(key:string)=>key.replace(/([a-z])([A-Z])/g,"$1 $2").replace(/[_-]+/g," ").replace(/^./,c=>c.toUpperCase());
function Value({value}:{value:unknown}){if(value===null||value===undefined)return <span>—</span>;if(typeof value==="string"||typeof value==="number"||typeof value==="boolean")return <span>{String(value)}</span>;if(Array.isArray(value)){if(!value.length)return <span>—</span>;if(value.every(item=>item&&typeof item==="object"&&!Array.isArray(item))){const rows=value as Record<string,unknown>[];const keys=Array.from(new Set(rows.flatMap(row=>Object.keys(row))));return <div className="table-wrap"><table><thead><tr>{keys.map(key=><th key={key}>{label(key)}</th>)}</tr></thead><tbody>{rows.map((row,index)=><tr key={index}>{keys.map(key=><td key={key}><Value value={row[key]}/></td>)}</tr>)}</tbody></table></div>}return <ul>{value.map((item,index)=><li key={index}><Value value={item}/></li>)}</ul>}if(typeof value==="object"){return <div style={{display:"grid",gap:10}}>{Object.entries(value as Record<string,unknown>).map(([key,item])=><div key={key} style={{display:"grid",gridTemplateColumns:"minmax(150px,220px) 1fr",gap:12,borderBottom:"1px solid #eee",paddingBottom:8}}><strong>{label(key)}</strong><Value value={item}/></div>)}</div>}return <span>{String(value)}</span>}
function Snapshot({value}:{value:unknown}){if(!value||typeof value!=="object")return <Value value={value}/>;return <Value value={value}/>}
export default function ParentReportCards(){const [data,setData]=useState<Data|null>(null);const [error,setError]=useState("");useEffect(()=>{fetch("/api/parent/report-cards",{cache:"no-store"}).then(async r=>{const b=await r.json();if(!r.ok)throw new Error(b.error);setData(b)}).catch(e=>setError(e.message||"Unable to load report cards."))},[]);return <main className="container" style={{maxWidth:1000}}><header className="admissions-header print-hide"><div><div className="eyebrow">Aghaaz / Parent Portal</div><h1>Report Cards</h1><p>Published report cards released by the school.</p></div><div style={{display:"flex",gap:8}}><button className="button" onClick={()=>window.print()}>Print</button><a className="button secondary" href="/parent">Back to dashboard</a></div></header>{error&&<div className="error print-hide">{error}</div>}{data?.reportCards.map(card=><article className="panel print-document" key={card.id} style={{marginBottom:20}}><header style={{borderBottom:"1px solid #ddd",paddingBottom:16,marginBottom:20}}><div className="eyebrow">{data.schoolName}</div><h2 style={{marginBottom:4}}>Report Card</h2><p style={{margin:0}}>{card.sessionName} · Released {fmt(card.releasedAt)}</p></header><Snapshot value={card.snapshot}/></article>)}{!error&&data&&!data.reportCards.length&&<section className="panel"><div className="empty-state">No published report cards are available yet.</div></section>}</main>}
