"use client";
import Link from "next/link";
import type { FormEvent } from "react";
import { useEffect, useState } from "react";

type Notice={id:string;title:string;message:string;audience:string;status:string;createdAt:string};
const channels=["IN_APP","EMAIL","SMS"];
export default function CommunicationPage(){
 const [items,setItems]=useState<Notice[]>([]),[title,setTitle]=useState(""),[message,setMessage]=useState(""),[audience,setAudience]=useState("ALL"),[error,setError]=useState(""),[noticeForDelivery,setNoticeForDelivery]=useState<Notice|null>(null),[selectedChannels,setSelectedChannels]=useState<string[]>(["IN_APP"]),[deliveryMessage,setDeliveryMessage]=useState("");
 const load=()=>fetch("/api/communication",{cache:"no-store"}).then(async r=>{const p=await r.json();if(!r.ok)throw new Error(p.error||"Unable to load notices.");setItems(Array.isArray(p)?p:[])}).catch(e=>setError(e instanceof Error?e.message:"Unable to load notices."));
 useEffect(()=>{void load()},[]);
 async function submit(e:FormEvent){e.preventDefault();setError("");const r=await fetch("/api/communication",{method:"POST",headers:{"Content-Type":"application/json"},body:JSON.stringify({title,message,audience})});const d=await r.json();if(!r.ok){setError(d.error||"Unable to publish notice");return}setTitle("");setMessage("");void load()}
 async function queueDelivery(){if(!noticeForDelivery)return;setError("");setDeliveryMessage("");const r=await fetch("/api/communication/deliver",{method:"POST",headers:{"Content-Type":"application/json"},body:JSON.stringify({noticeId:noticeForDelivery.id,audience:noticeForDelivery.audience,channels:selectedChannels})});const d=await r.json();if(!r.ok){setError(d.error||"Unable to queue delivery");return}setDeliveryMessage(`${d.recipientCount} recipient${d.recipientCount===1?"":"s"} resolved; ${d.queued} delivery${d.queued===1?"":"ies"} queued${d.failed?`; ${d.failed} failed due to missing contact details`:""}${d.skippedExisting?`; ${d.skippedExisting} already active`:""}. Email/SMS remain provider-pending until a provider is connected.`);setNoticeForDelivery(null)}
 return <main className="admissions-shell"><header className="admissions-header"><div><div className="eyebrow">Aghaaz School Management / Communication</div><h1>Communication</h1><p>Create, queue and audit school communications.</p></div><div style={{display:"flex",gap:8}}><Link className="button" href="/communication/templates">Templates</Link><Link className="button" href="/communication/history">Delivery History</Link><Link className="button" href="/communication/operations">Operations</Link></div></header>{error&&<div className="error">{error}</div>}{deliveryMessage&&<div className="empty-state">{deliveryMessage} <Link href="/communication/history">View history →</Link></div>}
 <section className="applications-card"><div className="table-toolbar"><div><h2>New notice</h2><p>Publish an announcement for students, parents or staff.</p></div></div><form className="form-grid" onSubmit={submit}><label>Title<input className="input" value={title} onChange={e=>setTitle(e.target.value)} required/></label><label>Audience<select className="input" value={audience} onChange={e=>setAudience(e.target.value)}><option>ALL</option><option>STUDENTS</option><option>PARENTS</option><option>STAFF</option><option>TEACHERS</option></select></label><label className="full">Message<textarea className="input" rows={5} value={message} onChange={e=>setMessage(e.target.value)} required/></label><button className="button" type="submit">Publish Notice</button></form></section>
 {noticeForDelivery&&<section className="applications-card"><div className="table-toolbar"><div><h2>Queue delivery</h2><p>{noticeForDelivery.title} · audience {noticeForDelivery.audience}</p></div><button className="button" type="button" onClick={()=>setNoticeForDelivery(null)}>Cancel</button></div><div className="form-grid"><label>Channels<select className="input" multiple value={selectedChannels} onChange={e=>setSelectedChannels(Array.from(e.target.selectedOptions).map(o=>o.value))}>{channels.map(c=><option key={c}>{c}</option>)}</select></label><div><p><strong>Recipient resolution</strong></p><small>Aghaaz resolves active students, their guardians, and active staff/teachers into individual delivery records. Missing email/phone details are recorded as failed instead of being reported as sent.</small></div></div><button className="button" type="button" disabled={!selectedChannels.length} onClick={()=>void queueDelivery()}>Resolve &amp; Queue Delivery</button></section>}
 <section className="applications-card"><div className="table-toolbar"><div><h2>Published notices</h2><p>{items.length} notice{items.length===1?"":"s"}</p></div></div>{items.length===0?<div className="empty-state">No notices yet.</div>:<div className="table-wrap"><table><thead><tr><th>Title</th><th>Audience</th><th>Status</th><th>Created</th><th>Action</th></tr></thead><tbody>{items.map(n=><tr key={n.id}><td><strong>{n.title}</strong><small>{n.message}</small></td><td>{n.audience}</td><td><span className={`status-pill status-${n.status.toLowerCase()}`}>{n.status}</span></td><td>{new Date(n.createdAt).toLocaleDateString()}</td><td>{n.status==="PUBLISHED"&&<button className="row-action" onClick={()=>{setNoticeForDelivery(n);setDeliveryMessage("")}}>Queue Delivery</button>}</td></tr>)}</tbody></table></div>}</section></main>
}