ALTER TABLE "Staff" ADD COLUMN "userId" TEXT;
CREATE UNIQUE INDEX "Staff_userId_key" ON "Staff"("userId");
ALTER TABLE "Staff" ADD CONSTRAINT "Staff_userId_fkey" FOREIGN KEY ("userId") REFERENCES "User"("id") ON DELETE SET NULL ON UPDATE CASCADE;
