"use client";
import Link from "next/link";
import {useEffect,useState} from "react";

type Student={id:string;application?:{studentName?:string}}; type Paper={id:string;className:string;subject:string;maxMarks:string;passMarks:string;results:{id:string;studentId:string;marks:string;grade?:string;student:Student}[]}; type Exam={id:string;name:string;status:string;papers:Paper[];session:{name:string}};
export default function ExamDetail({params}:{params:Promise<{id:string}>}){const [exam,setExam]=useState<Exam|null>(null);const [students,setStudents]=useState<Student[]>([]);const [marks,setMarks]=useState<Record<string,string>>({});const [error,setError]=useState("");
 const load=async()=>{const {id}=await params;const [a,b]=await Promise.all([fetch(`/api/exams/${id}`),fetch("/api/students")]);const x=await a.json();const s=await b.json();if(!a.ok){setError(x.error||"Unable to load exam");return}setExam(x);setStudents(s);const m:Record<string,string>={};x.papers.forEach((p:Paper)=>p.results.forEach(r=>m[`${p.id}:${r.studentId}`]=r.marks));setMarks(m)};useEffect(()=>{load()},[]);
 async function save(p:Paper,s:Student){const key=`${p.id}:${s.id}`;const r=await fetch("/api/results",{method:"POST",headers:{"Content-Type":"application/json"},body:JSON.stringify({paperId:p.id,studentId:s.id,marks:marks[key]})});if(!r.ok){const d=await r.json();setError(d.error||"Unable to save result");return}setError("");load()}
 if(!exam)return <main className="admissions-shell"><div className="empty-state">{error||"Loading examination…"}</div></main>;
 return <main className="admissions-shell"><header className="admissions-header"><div><div className="eyebrow">Examinations / {exam.session.name}</div><h1>{exam.name}</h1><p>{exam.papers.length} paper{exam.papers.length===1?"":"s"} · <span className={`status-pill status-${exam.status.toLowerCase()}`}>{exam.status}</span></p></div><Link className="button secondary" href="/results">Report Cards</Link></header>{error&&<div className="error">{error}</div>}{exam.papers.map(p=><section className="applications-card" key={p.id}><div className="table-toolbar"><div><h2>{p.subject} · {p.className}</h2><p>Maximum {p.maxMarks} · Pass {p.passMarks}</p></div></div><div className="table-wrap"><table><thead><tr><th>Student</th><th>Marks</th><th>Grade</th><th></th></tr></thead><tbody>{students.filter(s=>true).map(s=>{const key=`${p.id}:${s.id}`;const result=p.results.find(r=>r.studentId===s.id);return <tr key={s.id}><td><strong>{s.application?.studentName||"—"}</strong></td><td><input className="input marks-input" type="number" min="0" max={Number(p.maxMarks)} value={marks[key]??result?.marks??""} onChange={e=>setMarks({...marks,[key]:e.target.value})}/></td><td>{result?.grade||"—"}</td><td><button className="row-action" onClick={()=>save(p,s)}>Save</button></td></tr>})}</tbody></table></div></section>)}</main>}
