"use client";
import Link from "next/link";
import type { FormEvent } from "react";
import { useEffect, useState } from "react";

type Template = { id:string; name:string; channel:string; audience:string; subject:string|null; body:string; active:boolean };
export default function TemplatesPage(){
 const [items,setItems]=useState<Template[]>([]),[name,setName]=useState(""),[channel,setChannel]=useState("IN_APP"),[audience,setAudience]=useState("ALL"),[subject,setSubject]=useState(""),[body,setBody]=useState(""),[error,setError]=useState(""),[message,setMessage]=useState("");
 const load=()=>fetch("/api/communication/templates",{cache:"no-store"}).then(async r=>{const p=await r.json();if(!r.ok)throw new Error(p.error||"Unable to load templates.");setItems(p.templates||[])}).catch(e=>setError(e instanceof Error?e.message:"Unable to load templates."));
 useEffect(()=>{void load()},[]);
 async function submit(e:FormEvent){e.preventDefault();setError("");setMessage("");const r=await fetch("/api/communication/templates",{method:"POST",headers:{"Content-Type":"application/json"},body:JSON.stringify({name,channel,audience,subject,body})});const p=await r.json();if(!r.ok){setError(p.error||"Unable to create template");return}setMessage("Template saved.");setName("");setSubject("");setBody("");void load()}
 return <main className="admissions-shell"><header className="admissions-header"><div><div className="eyebrow">Aghaaz / Communication</div><h1>Templates</h1><p>Reusable message content for consistent school communication.</p></div><div style={{display:"flex",gap:8}}><Link className="button" href="/communication">Communication</Link><Link className="button" href="/communication/history">Delivery History</Link></div></header>{error&&<div className="error">{error}</div>}{message&&<div className="empty-state">{message}</div>}
 <section className="applications-card"><div className="table-toolbar"><div><h2>New template</h2><p>Keep the content reusable; delivery remains a separate operational step.</p></div></div><form className="form-grid" onSubmit={submit}><label>Name<input className="input" value={name} onChange={e=>setName(e.target.value)} required/></label><label>Channel<select className="input" value={channel} onChange={e=>setChannel(e.target.value)}><option>IN_APP</option><option>EMAIL</option><option>SMS</option></select></label><label>Audience<select className="input" value={audience} onChange={e=>setAudience(e.target.value)}><option>ALL</option><option>STUDENTS</option><option>PARENTS</option><option>STAFF</option></select></label><label>Subject<input className="input" value={subject} onChange={e=>setSubject(e.target.value)}/></label><label className="full">Body<textarea className="input" rows={5} value={body} onChange={e=>setBody(e.target.value)} required/></label><button className="button" type="submit">Save Template</button></form></section>
 <section className="applications-card"><div className="table-toolbar"><div><h2>Saved templates</h2><p>{items.length} active template{items.length===1?"":"s"}</p></div></div>{items.length===0?<div className="empty-state">No templates yet.</div>:<div className="table-wrap"><table><thead><tr><th>Name</th><th>Channel</th><th>Audience</th><th>Content</th></tr></thead><tbody>{items.map(t=><tr key={t.id}><td><strong>{t.name}</strong></td><td>{t.channel}</td><td>{t.audience}</td><td>{t.subject&&<small>{t.subject}</small>}<small>{t.body}</small></td></tr>)}</tbody></table></div>}</section></main>
}
