"use client";
import { useEffect, useMemo, useState } from "react";

type Student={id:string;application?:{studentName?:string;guardianName?:string};enrollment?:{id:string;className?:string;section?:string}}; type Record={id?:string;studentId:string;status:string;remarks?:string};
const states=["PRESENT","ABSENT","LATE","EXCUSED"];
export default function AttendancePage(){
 const [students,setStudents]=useState<Student[]>([]),[records,setRecords]=useState<Record[]>([]),[date,setDate]=useState(new Date().toISOString().slice(0,10)),[loading,setLoading]=useState(true),[saving,setSaving]=useState(false),[error,setError]=useState("");
 useEffect(()=>{Promise.all([fetch("/api/students").then(r=>r.json()),fetch(`/api/attendance?date=${date}`).then(r=>r.json())]).then(([s,a])=>{setStudents(s);setRecords(a.map((x:Record)=>x))}).catch(e=>setError(e.message||"Unable to load attendance")).finally(()=>setLoading(false))},[date]);
 const map=useMemo(()=>Object.fromEntries(records.map(r=>[r.studentId,r.status])),[records]);
 const setStatus=(id:string,status:string)=>setRecords(old=>[...old.filter(r=>r.studentId!==id),{studentId:id,status}]);
 async function save(){setSaving(true);setError("");try{const r=await fetch("/api/attendance",{method:"POST",headers:{"Content-Type":"application/json"},body:JSON.stringify({date,records:students.map(s=>({studentId:s.enrollment?.id||s.id,status:map[s.enrollment?.id||s.id]||"PRESENT"}))})});if(!r.ok)throw Error((await r.json()).error||"Unable to save attendance")}catch(e){setError(e instanceof Error?e.message:"Unable to save attendance")}finally{setSaving(false)}}
 return <main className="container"><header className="admissions-header"><div><div className="eyebrow">Aghaaz School Management / Attendance</div><h1>Daily Attendance</h1><p>Mark student attendance and save the register for a selected day.</p></div><button className="button" onClick={save} disabled={saving||loading}>{saving?"Saving…":"Save Attendance"}</button></header><section className="admission-stats"><div className="admission-stat"><span>Total students</span><strong>{students.length}</strong></div><div className="admission-stat"><span>Present</span><strong>{students.filter(s=>map[s.enrollment?.id||s.id]==="PRESENT").length}</strong></div><div className="admission-stat"><span>Absent</span><strong>{students.filter(s=>map[s.enrollment?.id||s.id]==="ABSENT").length}</strong></div><div className="admission-stat"><label>Date<input className="input" type="date" value={date} onChange={e=>{setLoading(true);setDate(e.target.value)}}/></label></div></section>{error&&<div className="error">{error}</div>}<section className="applications-card"><div className="table-toolbar"><div><h2>Attendance register</h2><p>{date}</p></div></div>{loading?<div className="empty-state">Loading attendance…</div>:<div className="table-wrap"><table><thead><tr><th>Student</th><th>Class</th><th>Guardian</th><th>Status</th></tr></thead><tbody>{students.map(s=>{const id=s.enrollment?.id||s.id;return <tr key={id}><td><strong>{s.application?.studentName||"—"}</strong></td><td>{s.enrollment?.className||"—"}{s.enrollment?.section&&<small>Section {s.enrollment.section}</small>}</td><td>{s.application?.guardianName||"—"}</td><td><select className="filter-select" value={map[id]||"PRESENT"} onChange={e=>setStatus(id,e.target.value)}>{states.map(x=><option key={x}>{x}</option>)}</select></td></tr>})}</tbody></table></div>}</section></main>;
}
