"use client";
import Link from "next/link";
import { useEffect, useMemo, useState } from "react";

type Signal={code:string;label:string;detail:string;href:string};
type Student={id:string;studentName:string;className:string;section:string|null;grNumber:string|null;priority:"HIGH"|"WATCH"|"MONITOR"|"CLEAR";signals:Signal[]};
type Data={generatedAt:string;thresholds:{attendancePercent:number;minimumAttendanceRecords:number};summary:{students:number;high:number;watch:number;monitor:number;clear:number};students:Student[]};

export default function StudentSupport(){
 const[data,setData]=useState<Data|null>(null),[q,setQ]=useState(""),[priority,setPriority]=useState("ALL"),[error,setError]=useState(""),[loading,setLoading]=useState(true);
 useEffect(()=>{fetch("/api/students/support",{cache:"no-store"}).then(async r=>{const d=await r.json();if(!r.ok)throw Error(d.error||"Unable to load support signals.");return d as Data}).then(setData).catch(e=>setError(e.message)).finally(()=>setLoading(false))},[]);
 const filtered=useMemo(()=>data?.students.filter(s=>(priority==="ALL"||s.priority===priority)&&[s.studentName,s.grNumber,s.className,s.section].join(" ").toLowerCase().includes(q.toLowerCase()))||[],[data,q,priority]);
 return <main className="container">
  <header className="admissions-header"><div><div className="eyebrow">Aghaaz / Students / Support</div><h1>Student Support Signals</h1><p>Bring attendance, fees, academics, homework and wellbeing together for timely follow-up.</p></div><div className="toolbar-actions"><Link className="button secondary" href="/students">Students</Link><Link className="button secondary" href="/monitor">Monitor</Link></div></header>
  {error&&<div className="error" role="alert">{error}</div>}
  <section className="admission-stats"><div className="admission-stat"><span>Active students</span><strong>{data?.summary.students??"—"}</strong></div><div className="admission-stat"><span>High priority</span><strong>{data?.summary.high??"—"}</strong></div><div className="admission-stat"><span>Watch</span><strong>{data?.summary.watch??"—"}</strong></div><div className="admission-stat"><span>Monitor</span><strong>{data?.summary.monitor??"—"}</strong></div></section>
  <section className="applications-card"><div className="table-toolbar"><div><h2>Support queue</h2><p>Signals are descriptive operational prompts, not a diagnosis or permanent student label.</p></div><div className="toolbar-actions"><input className="search-input" placeholder="Search student, GR or class…" value={q} onChange={e=>setQ(e.target.value)}/><select className="filter-select" value={priority} onChange={e=>setPriority(e.target.value)}><option value="ALL">All priorities</option><option value="HIGH">High</option><option value="WATCH">Watch</option><option value="MONITOR">Monitor</option><option value="CLEAR">Clear</option></select></div></div>
   {loading?<div className="empty-state">Generating support signals…</div>:filtered.length===0?<div className="empty-state">No students match the current filters.</div>:<div className="table-wrap"><table><thead><tr><th>Student</th><th>Class</th><th>Priority</th><th>Signals</th><th></th></tr></thead><tbody>{filtered.map(s=><tr key={s.id}><td><strong>{s.studentName}</strong><small>{s.grNumber||"No GR"}</small></td><td>{s.className}{s.section?<small>Section {s.section}</small>:null}</td><td><span className="status-pill">{s.priority}</span></td><td><div style={{display:"grid",gap:5}}>{s.signals.length?s.signals.map(x=><div key={x.code}><strong>{x.label}</strong><small>{x.detail}</small></div>):<small>No active support signal.</small>}</div></td><td><Link className="row-action" href={`/students/${s.id}`}>Student 360 →</Link></td></tr>)}</tbody></table></div>}
  </section>
  <section className="bottom-grid"><div className="panel"><div className="panel-heading"><div><h2>How signals are generated</h2><p>Transparent rules make the queue explainable.</p></div></div><div className="activity-row"><div><strong>Attendance</strong><small>At least {data?.thresholds.minimumAttendanceRecords??5} records in the last 30 days and below {data?.thresholds.attendancePercent??80}% attendance.</small></div></div><div className="activity-row"><div><strong>Fees</strong><small>Past-due invoice with a remaining balance after recorded payments.</small></div></div><div className="activity-row"><div><strong>Academics</strong><small>Published current-month result below the paper's configured pass mark.</small></div></div></div><div className="panel"><div className="panel-heading"><div><h2>Follow-up principle</h2><p>Use the signal to investigate the underlying record.</p></div></div><div className="activity-row"><div><strong>1. Review context</strong><small>Open Student 360 and inspect the underlying records.</small></div></div><div className="activity-row"><div><strong>2. Decide support</strong><small>Use teacher, family, academic or administrative follow-up as appropriate.</small></div></div><div className="activity-row"><div><strong>3. Record action</strong><small>Use Monitor Action Queue when an owned follow-up is required.</small></div></div></div></section>
 </main>;
}
